package com.junethewoods.variants.block;

import com.junethewoods.variants.Variants;
import com.junethewoods.variants.block.custom.*;
import com.junethewoods.variants.block.custom.end.*;
import com.junethewoods.variants.block.custom.nether.WarpedWartBlock;
import com.junethewoods.variants.util.VSBlockSetTypes;
import com.junethewoods.variants.util.VSWoodTypes;
import net.minecraft.util.valueproviders.UniformInt;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.grower.OakTreeGrower;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.MapColor;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredRegister;

public class VSBlocks {
    public static final DeferredRegister.Blocks BLOCKS = DeferredRegister.createBlocks(Variants.MOD_ID);

    public static final DeferredBlock<Block> PLAIN_BIRCH_BOOKSHELF = BLOCKS.register("plain_birch_bookshelf", () -> new VSBookshelfBlock(1, BlockBehaviour.Properties.copy(Blocks.BOOKSHELF)));
    public static final DeferredBlock<Block> PAINTING_LOG = BLOCKS.register("painting_log", () -> new RotatedPillarBlock(BlockBehaviour.Properties.copy(Blocks.OAK_LOG)));
    public static final DeferredBlock<Block> PAINTING_WOOD = BLOCKS.register("painting_wood", () -> new RotatedPillarBlock(BlockBehaviour.Properties.copy(Blocks.OAK_WOOD)));
    public static final DeferredBlock<Block> STRIPPED_PAINTING_LOG = BLOCKS.register("stripped_painting_log", () -> new RotatedPillarBlock(BlockBehaviour.Properties.copy(Blocks.STRIPPED_OAK_LOG)));
    public static final DeferredBlock<Block> STRIPPED_PAINTING_WOOD = BLOCKS.register("stripped_painting_wood", () -> new RotatedPillarBlock(BlockBehaviour.Properties.copy(Blocks.STRIPPED_OAK_WOOD)));
    public static final DeferredBlock<Block> PAINTING_LEAVES = BLOCKS.register("painting_leaves", () -> new LeavesBlock(BlockBehaviour.Properties.copy(Blocks.OAK_LEAVES)));
    public static final DeferredBlock<Block> PAINTING_SAPLING = BLOCKS.register("painting_sapling", () -> new SaplingBlock(new OakTreeGrower(), BlockBehaviour.Properties.copy(Blocks.OAK_SAPLING)));
    public static final DeferredBlock<Block> PAINTING_PLANKS = BLOCKS.register("painting_planks", () -> new Block(BlockBehaviour.Properties.copy(Blocks.OAK_PLANKS)));
    public static final DeferredBlock<Block> PAINTING_STAIRS = BLOCKS.register("painting_stairs", () -> new StairBlock(() -> VSBlocks.PAINTING_PLANKS.get().defaultBlockState(), BlockBehaviour.Properties.copy(Blocks.OAK_STAIRS)));
    public static final DeferredBlock<Block> PAINTING_SLAB = BLOCKS.register("painting_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(Blocks.OAK_SLAB)));
    public static final DeferredBlock<Block> PAINTING_FENCE = BLOCKS.register("painting_fence", () -> new FenceBlock(BlockBehaviour.Properties.copy(Blocks.OAK_FENCE)));
    public static final DeferredBlock<Block> PAINTING_FENCE_GATE = BLOCKS.register("painting_fence_gate", () -> new FenceGateBlock(BlockBehaviour.Properties.copy(Blocks.OAK_FENCE_GATE), VSWoodTypes.PAINTING));
    public static final DeferredBlock<Block> PAINTING_PRESSURE_PLATE = BLOCKS.register("painting_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, BlockBehaviour.Properties.copy(Blocks.OAK_PRESSURE_PLATE), VSBlockSetTypes.PAINTING));
    public static final DeferredBlock<Block> PAINTING_BUTTON = BLOCKS.register("painting_button", () -> new ButtonBlock(BlockBehaviour.Properties.copy(Blocks.OAK_BUTTON), VSBlockSetTypes.PAINTING, 30, true));
    public static final DeferredBlock<Block> PAINTING_TRAPDOOR = BLOCKS.register("painting_trapdoor", () -> new TrapDoorBlock(BlockBehaviour.Properties.copy(Blocks.OAK_TRAPDOOR), VSBlockSetTypes.PAINTING));
    public static final DeferredBlock<Block> PAINTING_TRAPDOOR_ALBAN = BLOCKS.register("alban_trapdoor", () -> new TrapDoorBlock(BlockBehaviour.Properties.copy(Blocks.OAK_TRAPDOOR), VSBlockSetTypes.PAINTING));
    public static final DeferredBlock<Block> PAINTING_TRAPDOOR_AZTEC = BLOCKS.register("aztec_trapdoor", () -> new TrapDoorBlock(BlockBehaviour.Properties.copy(Blocks.OAK_TRAPDOOR), VSBlockSetTypes.PAINTING));
    public static final DeferredBlock<Block> PAINTING_TRAPDOOR_AZTEC2 = BLOCKS.register("aztec2_trapdoor", () -> new TrapDoorBlock(BlockBehaviour.Properties.copy(Blocks.OAK_TRAPDOOR), VSBlockSetTypes.PAINTING));
    public static final DeferredBlock<Block> PAINTING_TRAPDOOR_BOMB = BLOCKS.register("bomb_trapdoor", () -> new TrapDoorBlock(BlockBehaviour.Properties.copy(Blocks.OAK_TRAPDOOR), VSBlockSetTypes.PAINTING));
    public static final DeferredBlock<Block> PAINTING_TRAPDOOR_KEBAB = BLOCKS.register("kebab_trapdoor", () -> new TrapDoorBlock(BlockBehaviour.Properties.copy(Blocks.OAK_TRAPDOOR), VSBlockSetTypes.PAINTING));
    public static final DeferredBlock<Block> PAINTING_TRAPDOOR_PLANT = BLOCKS.register("plant_trapdoor", () -> new TrapDoorBlock(BlockBehaviour.Properties.copy(Blocks.OAK_TRAPDOOR), VSBlockSetTypes.PAINTING));
    public static final DeferredBlock<Block> PAINTING_TRAPDOOR_WASTELAND = BLOCKS.register("wasteland_trapdoor", () -> new TrapDoorBlock(BlockBehaviour.Properties.copy(Blocks.OAK_TRAPDOOR), VSBlockSetTypes.PAINTING));
    public static final DeferredBlock<Block> PAINTING_DOOR = BLOCKS.register("painting_door", () -> new DoorBlock(BlockBehaviour.Properties.copy(Blocks.OAK_DOOR), VSBlockSetTypes.PAINTING));
    public static final DeferredBlock<Block> PAINTING_DOOR_WANDERER = BLOCKS.register("wanderer_door", () -> new DoorBlock(BlockBehaviour.Properties.copy(Blocks.OAK_DOOR), VSBlockSetTypes.PAINTING));
    public static final DeferredBlock<Block> PAINTING_DOOR_GRAHAM = BLOCKS.register("graham_door", () -> new DoorBlock(BlockBehaviour.Properties.copy(Blocks.OAK_DOOR), VSBlockSetTypes.PAINTING));
    public static final DeferredBlock<Block> PAINTING_DOOR_FIRST = BLOCKS.register("first_door", () -> new DoorBlock(BlockBehaviour.Properties.copy(Blocks.OAK_DOOR), VSBlockSetTypes.PAINTING));
    public static final DeferredBlock<Block> PAINTING_SIGN = BLOCKS.register("painting_sign", () -> new VSStandingSignBlock(BlockBehaviour.Properties.copy(Blocks.OAK_SIGN), VSWoodTypes.PAINTING));
    public static final DeferredBlock<Block> PAINTING_WALL_SIGN = BLOCKS.register("painting_wall_sign", () -> new VSWallSignBlock(BlockBehaviour.Properties.copy(Blocks.OAK_WALL_SIGN).lootFrom(VSBlocks.PAINTING_SIGN), VSWoodTypes.PAINTING));
    public static final DeferredBlock<Block> ENDERWOOD_STEM = BLOCKS.register("ender_stem", () -> new RotatedPillarBlock(BlockBehaviour.Properties.copy(Blocks.WARPED_STEM)));
    public static final DeferredBlock<Block> ENDERWOOD_HYPHAE = BLOCKS.register("ender_hyphae", () -> new RotatedPillarBlock(BlockBehaviour.Properties.copy(Blocks.WARPED_HYPHAE)));
    public static final DeferredBlock<Block> STRIPPED_ENDERWOOD_STEM = BLOCKS.register("stripped_ender_stem", () -> new RotatedPillarBlock(BlockBehaviour.Properties.copy(Blocks.STRIPPED_WARPED_STEM)));
    public static final DeferredBlock<Block> STRIPPED_ENDERWOOD_HYPHAE = BLOCKS.register("stripped_ender_hyphae", () -> new RotatedPillarBlock(BlockBehaviour.Properties.copy(Blocks.STRIPPED_WARPED_HYPHAE)));
    public static final DeferredBlock<Block> ENDER_WART_BLOCK = BLOCKS.register("ender_wart_block", () -> new Block(BlockBehaviour.Properties.copy(Blocks.WARPED_WART_BLOCK)));
    public static final DeferredBlock<Block> ENDERWOOD_PLANKS = BLOCKS.register("ender_planks", () -> new Block(BlockBehaviour.Properties.copy(Blocks.WARPED_PLANKS)));
    public static final DeferredBlock<Block> ENDERWOOD_BOOKSHELF = BLOCKS.register("ender_bookshelf", () -> new VSBookshelfBlock(2, BlockBehaviour.Properties.copy(Blocks.BOOKSHELF)));
    public static final DeferredBlock<Block> ENDERWOOD_STAIRS = BLOCKS.register("ender_stairs", () -> new StairBlock(() -> VSBlocks.ENDERWOOD_PLANKS.get().defaultBlockState(), BlockBehaviour.Properties.copy(Blocks.WARPED_STAIRS)));
    public static final DeferredBlock<Block> ENDERWOOD_SLAB = BLOCKS.register("ender_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(Blocks.WARPED_SLAB)));
    public static final DeferredBlock<Block> ENDERWOOD_FENCE = BLOCKS.register("ender_fence", () -> new FenceBlock(BlockBehaviour.Properties.copy(Blocks.WARPED_FENCE)));
    public static final DeferredBlock<Block> ENDERWOOD_FENCE_GATE = BLOCKS.register("ender_fence_gate", () -> new FenceGateBlock(BlockBehaviour.Properties.copy(Blocks.WARPED_FENCE_GATE), VSWoodTypes.ENDERWOOD));
    public static final DeferredBlock<Block> ENDERWOOD_PRESSURE_PLATE = BLOCKS.register("ender_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, BlockBehaviour.Properties.copy(Blocks.WARPED_PRESSURE_PLATE), VSBlockSetTypes.ENDERWOOD));
    public static final DeferredBlock<Block> ENDERWOOD_BUTTON = BLOCKS.register("ender_button", () -> new ButtonBlock(BlockBehaviour.Properties.copy(Blocks.WARPED_BUTTON), VSBlockSetTypes.ENDERWOOD, 30, true));
    public static final DeferredBlock<Block> ENDERWOOD_TRAPDOOR = BLOCKS.register("ender_trapdoor", () -> new TrapDoorBlock(BlockBehaviour.Properties.copy(Blocks.WARPED_TRAPDOOR), VSBlockSetTypes.ENDERWOOD));
    public static final DeferredBlock<Block> ENDERWOOD_DOOR = BLOCKS.register("ender_door", () -> new DoorBlock(BlockBehaviour.Properties.copy(Blocks.WARPED_DOOR), VSBlockSetTypes.ENDERWOOD));
    public static final DeferredBlock<Block> ENDERWOOD_SIGN = BLOCKS.register("ender_sign", () -> new VSStandingSignBlock(BlockBehaviour.Properties.copy(Blocks.OAK_SIGN), VSWoodTypes.ENDERWOOD));
    public static final DeferredBlock<Block> ENDERWOOD_WALL_SIGN = BLOCKS.register("ender_wall_sign", () -> new VSWallSignBlock(BlockBehaviour.Properties.copy(Blocks.OAK_WALL_SIGN).lootFrom(VSBlocks.ENDERWOOD_SIGN), VSWoodTypes.ENDERWOOD));
    public static final DeferredBlock<Block> ELDER_SEA_LANTERN = BLOCKS.register("elder_sea_lantern", () -> new ConduitFrameBlock(BlockBehaviour.Properties.copy(Blocks.SEA_LANTERN)));
    public static final DeferredBlock<Block> ELDER_PRISMARINE = BLOCKS.register("elder_prismarine", () -> new ConduitFrameBlock(BlockBehaviour.Properties.copy(Blocks.PRISMARINE)));
    public static final DeferredBlock<Block> ELDER_PRISMARINE_STAIRS = BLOCKS.register("elder_prismarine_stairs", () -> new StairBlock(() -> VSBlocks.ELDER_PRISMARINE.get().defaultBlockState(), BlockBehaviour.Properties.copy(Blocks.PRISMARINE_STAIRS)));
    public static final DeferredBlock<Block> ELDER_PRISMARINE_SLAB = BLOCKS.register("elder_prismarine_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(Blocks.PRISMARINE_SLAB)));
    public static final DeferredBlock<Block> ELDER_PRISMARINE_WALL = BLOCKS.register("elder_prismarine_wall", () -> new WallBlock(BlockBehaviour.Properties.copy(Blocks.PRISMARINE_WALL)));
    public static final DeferredBlock<Block> ELDER_PRISMARINE_BRICKS = BLOCKS.register("elder_prismarine_bricks", () -> new ConduitFrameBlock(BlockBehaviour.Properties.copy(Blocks.PRISMARINE_BRICKS)));
    public static final DeferredBlock<Block> ELDER_PRISMARINE_BRICK_STAIRS = BLOCKS.register("elder_prismarine_brick_stairs", () -> new StairBlock(() -> VSBlocks.ELDER_PRISMARINE_BRICKS.get().defaultBlockState(), BlockBehaviour.Properties.copy(Blocks.PRISMARINE_BRICK_STAIRS)));
    public static final DeferredBlock<Block> ELDER_PRISMARINE_BRICK_SLAB = BLOCKS.register("elder_prismarine_brick_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(Blocks.PRISMARINE_BRICK_SLAB)));
    public static final DeferredBlock<Block> DARK_ELDER_PRISMARINE = BLOCKS.register("dark_elder_prismarine", () -> new ConduitFrameBlock(BlockBehaviour.Properties.copy(Blocks.DARK_PRISMARINE)));
    public static final DeferredBlock<Block> DARK_ELDER_PRISMARINE_STAIRS = BLOCKS.register("dark_elder_prismarine_stairs", () -> new StairBlock(() -> VSBlocks.DARK_ELDER_PRISMARINE.get().defaultBlockState(), BlockBehaviour.Properties.copy(Blocks.DARK_PRISMARINE_STAIRS)));
    public static final DeferredBlock<Block> DARK_ELDER_PRISMARINE_SLAB = BLOCKS.register("dark_elder_prismarine_slab", () -> new SlabBlock(BlockBehaviour.Properties.copy(Blocks.DARK_PRISMARINE_SLAB)));
    public static final DeferredBlock<Block> CHISELED_END_STONE_BRICKS = BLOCKS.register("chiseled_end_stone_bricks", () -> new Block(BlockBehaviour.Properties.copy(Blocks.END_STONE_BRICKS)));
    public static final DeferredBlock<Block> INFESTED_CHISELED_END_STONE_BRICKS = BLOCKS.register("infested_chiseled_end_stone_bricks", () -> new InfestedBlock(VSBlocks.CHISELED_END_STONE_BRICKS.get(), BlockBehaviour.Properties.of().mapColor(MapColor.SAND).strength(0, 0.75F)));
    public static final DeferredBlock<Block> CHISELED_PURPUR_BLOCK = BLOCKS.register("chiseled_purpur_block", () -> new Block(BlockBehaviour.Properties.copy(Blocks.PURPUR_BLOCK)));
    public static final DeferredBlock<Block> INFESTED_CHISELED_PURPUR_BLOCK = BLOCKS.register("infested_chiseled_purpur_block", () -> new InfestedBlock(VSBlocks.CHISELED_PURPUR_BLOCK.get(), BlockBehaviour.Properties.of().mapColor(DyeColor.MAGENTA).strength(0, 0.75F)));
    public static final DeferredBlock<Block> RED_NETHER_BRICK_FENCE = BLOCKS.register("red_nether_brick_fence", () -> new FenceBlock(BlockBehaviour.Properties.copy(Blocks.NETHER_BRICK_FENCE)));
    public static final DeferredBlock<Block> WITHER_BONE_BLOCK = BLOCKS.register("wither_bone_block", () -> new RotatedPillarBlock(BlockBehaviour.Properties.copy(Blocks.BONE_BLOCK)));
    public static final DeferredBlock<Block> RAW_DEBRIS_BLOCK = BLOCKS.register("raw_debris_block", () -> new Block(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_BLACK).requiresCorrectToolForDrops().strength(30f, 1200f).sound(SoundType.ANCIENT_DEBRIS)));
    public static final DeferredBlock<Block> QUARTZ_ORE = BLOCKS.register("quartz_ore", () -> new DropExperienceBlock(BlockBehaviour.Properties.of().mapColor(MapColor.STONE).requiresCorrectToolForDrops().strength(3f, 3f), UniformInt.of(2, 5)));
    public static final DeferredBlock<Block> DEEPSLATE_QUARTZ_ORE = BLOCKS.register("deepslate_quartz_ore", () -> new DropExperienceBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_GRAY).requiresCorrectToolForDrops().strength(4.5f, 3f)));
    public static final DeferredBlock<Block> END_QUARTZ_ORE = BLOCKS.register("end_quartz_ore", () -> new DropExperienceBlock(BlockBehaviour.Properties.of().mapColor(MapColor.SAND).requiresCorrectToolForDrops().strength(3f, 9f), UniformInt.of(2, 5)));
    public static final DeferredBlock<Block> GOLDEN_CAULDRON = BLOCKS.register("gold_cauldron", () -> new CauldronBlock(BlockBehaviour.Properties.copy(Blocks.GOLD_BLOCK).noOcclusion()));
    public static final DeferredBlock<Block> GOLDEN_BEACON = BLOCKS.register("gold_beacon", () -> new VSBeaconBlock(DyeColor.YELLOW, BlockBehaviour.Properties.copy(Blocks.BEACON)));
    public static final DeferredBlock<Block> DIAMOND_BELL = BLOCKS.register("diamond_bell", () -> new VSBellBlock(BlockBehaviour.Properties.copy(Blocks.BELL)));
    public static final DeferredBlock<Block> NETHERRACK_LEVER = BLOCKS.register("netherrack_lever", () -> new LeverBlock(BlockBehaviour.Properties.copy(Blocks.LEVER).sound(SoundType.NETHERRACK)));
    public static final DeferredBlock<Block> END_STONE_LEVER = BLOCKS.register("end_stone_lever", () -> new LeverBlock(BlockBehaviour.Properties.copy(Blocks.LEVER).sound(SoundType.STONE)));
    public static final DeferredBlock<Block> GLOW_BLACK_WOOL = BLOCKS.register("glow_black_wool", () -> new Block(BlockBehaviour.Properties.copy(Blocks.LIGHT_BLUE_WOOL)));
    public static final DeferredBlock<Block> GLOW_BLACK_CARPET = BLOCKS.register("glow_black_carpet", () -> new CarpetBlock(BlockBehaviour.Properties.copy(Blocks.LIGHT_BLUE_CARPET)));
    public static final DeferredBlock<Block> GLOW_BLACK_BED = BLOCKS.register("glow_black_bed", () -> new VSBedBlock(DyeColor.LIGHT_BLUE, BlockBehaviour.Properties.copy(Blocks.LIGHT_BLUE_BED)));
    public static final DeferredBlock<Block> GLOW_BLACK_STAINED_GLASS = BLOCKS.register("glow_black_stained_glass", () -> new HexBeamStainedGlassBlock(0x4bdeba, BlockBehaviour.Properties.copy(Blocks.LIGHT_BLUE_STAINED_GLASS)));
    public static final DeferredBlock<Block> GLOW_BLACK_STAINED_GLASS_PANE = BLOCKS.register("glow_black_stained_glass_pane", () -> new HexBeamStainedGlassPaneBlock(0x4bdeba, BlockBehaviour.Properties.copy(Blocks.LIGHT_BLUE_STAINED_GLASS_PANE)));
    public static final DeferredBlock<Block> QUARTZ_GLASS = BLOCKS.register("quartz_glass", () -> new HexBeamStainedGlassBlock(0xddd4c6, BlockBehaviour.Properties.copy(Blocks.GLASS)));
    public static final DeferredBlock<Block> QUARTZ_GLASS_PANE = BLOCKS.register("quartz_glass_pane", () -> new HexBeamStainedGlassPaneBlock(0xddd4c6, BlockBehaviour.Properties.copy(Blocks.GLASS_PANE)));
    public static final DeferredBlock<Block> QUARTZ_BARS = BLOCKS.register("quartz_bars", () -> new IronBarsBlock(BlockBehaviour.Properties.copy(Blocks.IRON_BARS)));
    public static final DeferredBlock<Block> QUARTZ_CHAIN = BLOCKS.register("quartz_chain", () -> new ChainBlock(BlockBehaviour.Properties.copy(Blocks.CHAIN)));
    public static final DeferredBlock<Block> GOLDEN_CHAIN = BLOCKS.register("golden_chain", () -> new ChainBlock(BlockBehaviour.Properties.copy(Blocks.CHAIN)));
    public static final DeferredBlock<Block> DIAMOND_CHAIN = BLOCKS.register("diamond_chain", () -> new ChainBlock(BlockBehaviour.Properties.copy(Blocks.CHAIN)));
    public static final DeferredBlock<Block> EMERALD_CHAIN = BLOCKS.register("emerald_chain", () -> new ChainBlock(BlockBehaviour.Properties.copy(Blocks.CHAIN)));
    public static final DeferredBlock<Block> ENDER_NYLIUM = BLOCKS.register("ender_nylium", () -> new EnderNyliumBlock(BlockBehaviour.Properties.copy(Blocks.CRIMSON_NYLIUM)));
    public static final DeferredBlock<Block> ENDER_FARMLAND = BLOCKS.register("ender_farmland", () -> new EnderFarmlandBlock(BlockBehaviour.Properties.copy(Blocks.CRIMSON_NYLIUM).randomTicks().isViewBlocking((state, world, pos) -> true).isSuffocating((state, world, pos) -> true)));
    public static final DeferredBlock<Block> ENDER_ROOTS = BLOCKS.register("ender_roots", () -> new EnderRootsBlock(BlockBehaviour.Properties.copy(Blocks.CRIMSON_ROOTS)));
    public static final DeferredBlock<Block> END_SPROUTS = BLOCKS.register("ender_sprouts", () -> new EndSproutsBlock(BlockBehaviour.Properties.copy(Blocks.NETHER_SPROUTS)));
    public static final DeferredBlock<Block> ENDER_FUNGUS = BLOCKS.register("ender_fungus", () -> new EnderFungusBlock(BlockBehaviour.Properties.copy(Blocks.CRIMSON_FUNGUS)));
    public static final DeferredBlock<Block> WARPING_VINES = BLOCKS.register("warping_vines", () -> new WarpingVinesTopBlock(BlockBehaviour.Properties.copy(Blocks.WEEPING_VINES)));
    public static final DeferredBlock<Block> WARPING_VINES_PLANT = BLOCKS.register("warping_vines_plant", () -> new WarpingVinesBlock(BlockBehaviour.Properties.copy(Blocks.WEEPING_VINES_PLANT)));
    public static final DeferredBlock<Block> GOLDEN_CARROTS = BLOCKS.register("golden_carrots", () -> new GoldenCarrotsBlock(BlockBehaviour.Properties.of().noCollission().randomTicks().instabreak().sound(SoundType.CROP)));
    public static final DeferredBlock<Block> GLOW_BLACK_TULIP = BLOCKS.register("glow_black_tulip", () -> new FlowerBlock(() -> MobEffects.GLOWING, 7, BlockBehaviour.Properties.of().noCollission().instabreak().sound(SoundType.CROP)));
    public static final DeferredBlock<Block> SUNNY_FLOWER = BLOCKS.register("sunny_flower", () -> new FlowerBlock(() -> MobEffects.INVISIBILITY, 9, BlockBehaviour.Properties.of().noCollission().instabreak().sound(SoundType.CROP)));
    public static final DeferredBlock<Block> GLOW_BERRY_BUSH = BLOCKS.register("glow_berry_bush", () -> new SweetBerryBushBlock(BlockBehaviour.Properties.copy(Blocks.SWEET_BERRY_BUSH)));
    public static final DeferredBlock<Block> WARPED_WART = BLOCKS.register("warped_wart", () -> new WarpedWartBlock(BlockBehaviour.Properties.of().mapColor(MapColor.WARPED_WART_BLOCK).noCollission().randomTicks().sound(SoundType.FUNGUS)));
    public static final DeferredBlock<Block> ENDER_WART = BLOCKS.register("ender_wart", () -> new EnderWartBlock(BlockBehaviour.Properties.of().mapColor(MapColor.COLOR_PURPLE).noCollission().randomTicks().sound(SoundType.FUNGUS)));
    public static final DeferredBlock<Block> POTTED_SUGAR_CANE = BLOCKS.register("potted_sugar_cane", () -> new FlowerPotBlock(Blocks.SUGAR_CANE, BlockBehaviour.Properties.of().instabreak().noOcclusion()));
    public static final DeferredBlock<Block> POTTED_GLOW_BLACK_TULIP = BLOCKS.register("potted_glow_black_tulip", () -> new FlowerPotBlock(VSBlocks.GLOW_BLACK_TULIP.get(), BlockBehaviour.Properties.of().instabreak().noOcclusion()));
    public static final DeferredBlock<Block> POTTED_SUNNY_FLOWER = BLOCKS.register("potted_sunny_flower", () -> new FlowerPotBlock(VSBlocks.SUNNY_FLOWER.get(), BlockBehaviour.Properties.of().instabreak().noOcclusion()));
    public static final DeferredBlock<Block> POTTED_PAINTING_SAPLING = BLOCKS.register("potted_painting_sapling", () -> new FlowerPotBlock(VSBlocks.PAINTING_SAPLING.get(), BlockBehaviour.Properties.of().instabreak().noOcclusion()));
    public static final DeferredBlock<Block> POTTED_ENDER_ROOTS = BLOCKS.register("potted_ender_roots", () -> new FlowerPotBlock(VSBlocks.ENDER_ROOTS.get(), BlockBehaviour.Properties.of().instabreak().noOcclusion()));
    public static final DeferredBlock<Block> POTTED_ENDER_FUNGUS = BLOCKS.register("potted_ender_fungus", () -> new FlowerPotBlock(VSBlocks.ENDER_FUNGUS.get(), BlockBehaviour.Properties.of().instabreak().noOcclusion()));
//    public static final DeferredBlock<FlowingFluidBlock> SOUL_LAVA = BLOCKS.register("soul_lava", () -> new FlowingFluidBlock(VSFluids.SOUL_LAVA, BlockBehaviour.Properties.of(Material.LAVA, MaterialColor.COLOR_LIGHT_BLUE).noCollission().randomTicks().strength(100).lightLevel((light) -> 15).noDrops()));
}
