package com.junethewoods.variants.core.init;

import com.junethewoods.variants.common.item.CustomSusSoupItem;
import com.junethewoods.variants.common.item.VariantFoods;
import com.junethewoods.variants.core.Variants;
import com.junethewoods.variants.common.item.CustomSoupItem;
import com.junethewoods.variants.core.tabs.VariantTab;
import net.minecraft.item.Foods;
import net.minecraft.item.Item;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class BowlInit {
    public static final DeferredRegister<Item> items = DeferredRegister.create(ForgeRegistries.ITEMS, Variants.mod_id);

    public static final RegistryObject<Item> oak_beetroot_soup = items.register("oak_beetroot_soup", () -> new CustomSoupItem.OakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.BEETROOT_SOUP)));
    public static final RegistryObject<Item> spruce_beetroot_soup = items.register("spruce_beetroot_soup", () -> new CustomSoupItem.SpruceBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.BEETROOT_SOUP)));
    public static final RegistryObject<Item> birch_beetroot_soup = items.register("birch_beetroot_soup", () -> new CustomSoupItem.BirchBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.BEETROOT_SOUP)));
    public static final RegistryObject<Item> jungle_beetroot_soup = items.register("jungle_beetroot_soup", () -> new CustomSoupItem.JungleBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.BEETROOT_SOUP)));
    public static final RegistryObject<Item> acacia_beetroot_soup = items.register("acacia_beetroot_soup", () -> new CustomSoupItem.AcaciaBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.BEETROOT_SOUP)));
    public static final RegistryObject<Item> dark_oak_beetroot_soup = items.register("dark_oak_beetroot_soup", () -> new CustomSoupItem.DarkOakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.BEETROOT_SOUP)));
    public static final RegistryObject<Item> crimson_beetroot_soup = items.register("crimson_beetroot_soup", () -> new CustomSoupItem.CrimsonBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.BEETROOT_SOUP)));
    public static final RegistryObject<Item> warped_beetroot_soup = items.register("warped_beetroot_soup", () -> new CustomSoupItem.WarpedBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.BEETROOT_SOUP)));
    public static final RegistryObject<Item> painting_beetroot_soup = items.register("painting_beetroot_soup", () -> new CustomSoupItem.PaintingBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.BEETROOT_SOUP)));
    public static final RegistryObject<Item> ender_beetroot_soup = items.register("ender_beetroot_soup", () -> new CustomSoupItem.EnderBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.BEETROOT_SOUP)));
    public static final RegistryObject<Item> oak_mushroom_stew = items.register("oak_mushroom_stew", () -> new CustomSoupItem.OakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> spruce_mushroom_stew = items.register("spruce_mushroom_stew", () -> new CustomSoupItem.SpruceBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> birch_mushroom_stew = items.register("birch_mushroom_stew", () -> new CustomSoupItem.BirchBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> jungle_mushroom_stew = items.register("jungle_mushroom_stew", () -> new CustomSoupItem.JungleBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> acacia_mushroom_stew = items.register("acacia_mushroom_stew", () -> new CustomSoupItem.AcaciaBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> dark_oak_mushroom_stew = items.register("dark_oak_mushroom_stew", () -> new CustomSoupItem.DarkOakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> crimson_mushroom_stew = items.register("crimson_mushroom_stew", () -> new CustomSoupItem.CrimsonBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> warped_mushroom_stew = items.register("warped_mushroom_stew", () -> new CustomSoupItem.WarpedBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> painting_mushroom_stew = items.register("painting_mushroom_stew", () -> new CustomSoupItem.PaintingBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> ender_mushroom_stew = items.register("ender_mushroom_stew", () -> new CustomSoupItem.EnderBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> oak_rabbit_stew = items.register("oak_rabbit_stew", () -> new CustomSoupItem.OakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.RABBIT_STEW)));
    public static final RegistryObject<Item> spruce_rabbit_stew = items.register("spruce_rabbit_stew", () -> new CustomSoupItem.SpruceBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.RABBIT_STEW)));
    public static final RegistryObject<Item> birch_rabbit_stew = items.register("birch_rabbit_stew", () -> new CustomSoupItem.BirchBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.RABBIT_STEW)));
    public static final RegistryObject<Item> jungle_rabbit_stew = items.register("jungle_rabbit_stew", () -> new CustomSoupItem.JungleBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.RABBIT_STEW)));
    public static final RegistryObject<Item> acacia_rabbit_stew = items.register("acacia_rabbit_stew", () -> new CustomSoupItem.AcaciaBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.RABBIT_STEW)));
    public static final RegistryObject<Item> dark_oak_rabbit_stew = items.register("dark_oak_rabbit_stew", () -> new CustomSoupItem.DarkOakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.RABBIT_STEW)));
    public static final RegistryObject<Item> crimson_rabbit_stew = items.register("crimson_rabbit_stew", () -> new CustomSoupItem.CrimsonBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.RABBIT_STEW)));
    public static final RegistryObject<Item> warped_rabbit_stew = items.register("warped_rabbit_stew", () -> new CustomSoupItem.WarpedBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.RABBIT_STEW)));
    public static final RegistryObject<Item> painting_rabbit_stew = items.register("painting_rabbit_stew", () -> new CustomSoupItem.PaintingBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.RABBIT_STEW)));
    public static final RegistryObject<Item> ender_rabbit_stew = items.register("ender_rabbit_stew", () -> new CustomSoupItem.EnderBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.RABBIT_STEW)));
    public static final RegistryObject<Item> oak_fungi_stew = items.register("oak_fungi_stew", () -> new CustomSoupItem.OakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> spruce_fungi_stew = items.register("spruce_fungi_stew", () -> new CustomSoupItem.SpruceBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> birch_fungi_stew = items.register("birch_fungi_stew", () -> new CustomSoupItem.BirchBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> jungle_fungi_stew = items.register("jungle_fungi_stew", () -> new CustomSoupItem.JungleBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> acacia_fungi_stew = items.register("acacia_fungi_stew", () -> new CustomSoupItem.AcaciaBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> dark_oak_fungi_stew = items.register("dark_oak_fungi_stew", () -> new CustomSoupItem.DarkOakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> crimson_fungi_stew = items.register("crimson_fungi_stew", () -> new CustomSoupItem.CrimsonBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> warped_fungi_stew = items.register("warped_fungi_stew", () -> new CustomSoupItem.WarpedBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> painting_fungi_stew = items.register("painting_fungi_stew", () -> new CustomSoupItem.PaintingBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> ender_fungi_stew = items.register("ender_fungi_stew", () -> new CustomSoupItem.EnderBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> oak_end_fungi_stew = items.register("oak_end_fungi_stew", () -> new CustomSoupItem.OakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> spruce_end_fungi_stew = items.register("spruce_end_fungi_stew", () -> new CustomSoupItem.SpruceBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> birch_end_fungi_stew = items.register("birch_end_fungi_stew", () -> new CustomSoupItem.BirchBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> jungle_end_fungi_stew = items.register("jungle_end_fungi_stew", () -> new CustomSoupItem.JungleBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> acacia_end_fungi_stew = items.register("acacia_end_fungi_stew", () -> new CustomSoupItem.AcaciaBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> dark_oak_end_fungi_stew = items.register("dark_oak_end_fungi_stew", () -> new CustomSoupItem.DarkOakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> crimson_end_fungi_stew = items.register("crimson_end_fungi_stew", () -> new CustomSoupItem.CrimsonBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> warped_end_fungi_stew = items.register("warped_end_fungi_stew", () -> new CustomSoupItem.WarpedBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> painting_end_fungi_stew = items.register("painting_end_fungi_stew", () -> new CustomSoupItem.PaintingBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> ender_end_fungi_stew = items.register("ender_end_fungi_stew", () -> new CustomSoupItem.EnderBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> oak_suspicious_stew = items.register("oak_suspicious_stew", () -> new CustomSoupItem.OakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> spruce_suspicious_stew = items.register("spruce_suspicious_stew", () -> new CustomSusSoupItem.SpruceBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> birch_suspicious_stew = items.register("birch_suspicious_stew", () -> new CustomSusSoupItem.BirchBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> jungle_suspicious_stew = items.register("jungle_suspicious_stew", () -> new CustomSusSoupItem.JungleBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> acacia_suspicious_stew = items.register("acacia_suspicious_stew", () -> new CustomSusSoupItem.AcaciaBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> dark_oak_suspicious_stew = items.register("dark_oak_suspicious_stew", () -> new CustomSusSoupItem.DarkOakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> crimson_suspicious_stew = items.register("crimson_suspicious_stew", () -> new CustomSusSoupItem.CrimsonBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> warped_suspicious_stew = items.register("warped_suspicious_stew", () -> new CustomSusSoupItem.WarpedBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> painting_suspicious_stew = items.register("painting_suspicious_stew", () -> new CustomSusSoupItem.PaintingBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> ender_suspicious_stew = items.register("ender_suspicious_stew", () -> new CustomSusSoupItem.EnderBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.MUSHROOM_STEW)));

    public static final RegistryObject<Item> oak_water_stew = items.register("oak_water_stew", () -> new CustomSoupItem.OakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.water_bowl)));
    public static final RegistryObject<Item> spruce_water_stew = items.register("spruce_water_stew", () -> new CustomSoupItem.SpruceBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.water_bowl)));
    public static final RegistryObject<Item> birch_water_stew = items.register("birch_water_stew", () -> new CustomSoupItem.BirchBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.water_bowl)));
    public static final RegistryObject<Item> jungle_water_stew = items.register("jungle_water_stew", () -> new CustomSoupItem.JungleBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.water_bowl)));
    public static final RegistryObject<Item> acacia_water_stew = items.register("acacia_water_stew", () -> new CustomSoupItem.AcaciaBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.water_bowl)));
    public static final RegistryObject<Item> dark_oak_water_stew = items.register("dark_oak_water_stew", () -> new CustomSoupItem.DarkOakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.water_bowl)));
    public static final RegistryObject<Item> crimson_water_stew = items.register("crimson_water_stew", () -> new CustomSoupItem.CrimsonBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.water_bowl)));
    public static final RegistryObject<Item> warped_water_stew = items.register("warped_water_stew", () -> new CustomSoupItem.WarpedBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.water_bowl)));
    public static final RegistryObject<Item> painting_water_stew = items.register("painting_water_stew", () -> new CustomSoupItem.PaintingBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.water_bowl)));
    public static final RegistryObject<Item> ender_water_stew = items.register("ender_water_stew", () -> new CustomSoupItem.EnderBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.water_bowl)));

    public static final RegistryObject<Item> oak_lava_stew = items.register("oak_lava_stew", () -> new CustomSoupItem.OakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.lava_bowl)));
    public static final RegistryObject<Item> spruce_lava_stew = items.register("spruce_lava_stew", () -> new CustomSoupItem.SpruceBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.lava_bowl)));
    public static final RegistryObject<Item> birch_lava_stew = items.register("birch_lava_stew", () -> new CustomSoupItem.BirchBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.lava_bowl)));
    public static final RegistryObject<Item> jungle_lava_stew = items.register("jungle_lava_stew", () -> new CustomSoupItem.JungleBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.lava_bowl)));
    public static final RegistryObject<Item> acacia_lava_stew = items.register("acacia_lava_stew", () -> new CustomSoupItem.AcaciaBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.lava_bowl)));
    public static final RegistryObject<Item> dark_oak_lava_stew = items.register("dark_oak_lava_stew", () -> new CustomSoupItem.DarkOakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.lava_bowl)));
    public static final RegistryObject<Item> crimson_lava_stew = items.register("crimson_lava_stew", () -> new CustomSoupItem.CrimsonBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.lava_bowl)));
    public static final RegistryObject<Item> warped_lava_stew = items.register("warped_lava_stew", () -> new CustomSoupItem.WarpedBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.lava_bowl)));
    public static final RegistryObject<Item> painting_lava_stew = items.register("painting_lava_stew", () -> new CustomSoupItem.PaintingBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.lava_bowl)));
    public static final RegistryObject<Item> ender_lava_stew = items.register("ender_lava_stew", () -> new CustomSoupItem.EnderBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.lava_bowl)));

    public static final RegistryObject<Item> oak_milk_stew = items.register("oak_milk_stew", () -> new CustomSoupItem.OakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.standard_bowl)));
    public static final RegistryObject<Item> spruce_milk_stew = items.register("spruce_milk_stew", () -> new CustomSoupItem.SpruceBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.standard_bowl)));
    public static final RegistryObject<Item> birch_milk_stew = items.register("birch_milk_stew", () -> new CustomSoupItem.BirchBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.standard_bowl)));
    public static final RegistryObject<Item> jungle_milk_stew = items.register("jungle_milk_stew", () -> new CustomSoupItem.JungleBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.standard_bowl)));
    public static final RegistryObject<Item> acacia_milk_stew = items.register("acacia_milk_stew", () -> new CustomSoupItem.AcaciaBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.standard_bowl)));
    public static final RegistryObject<Item> dark_oak_milk_stew = items.register("dark_oak_milk_stew", () -> new CustomSoupItem.DarkOakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.standard_bowl)));
    public static final RegistryObject<Item> crimson_milk_stew = items.register("crimson_milk_stew", () -> new CustomSoupItem.CrimsonBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.standard_bowl)));
    public static final RegistryObject<Item> warped_milk_stew = items.register("warped_milk_stew", () -> new CustomSoupItem.WarpedBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.standard_bowl)));
    public static final RegistryObject<Item> painting_milk_stew = items.register("painting_milk_stew", () -> new CustomSoupItem.PaintingBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.standard_bowl)));
    public static final RegistryObject<Item> ender_milk_stew = items.register("ender_milk_stew", () -> new CustomSoupItem.EnderBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(VariantFoods.standard_bowl)));

    public static final RegistryObject<Item> oak_powder_snow_stew = items.register("oak_powder_snow_stew", () -> new CustomSoupItem.OakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.APPLE)));
    public static final RegistryObject<Item> spruce_powder_snow_stew = items.register("spruce_powder_snow_stew", () -> new CustomSoupItem.SpruceBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.APPLE)));
    public static final RegistryObject<Item> birch_powder_snow_stew = items.register("birch_powder_snow_stew", () -> new CustomSoupItem.BirchBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.APPLE)));
    public static final RegistryObject<Item> jungle_powder_snow_stew = items.register("jungle_powder_snow_stew", () -> new CustomSoupItem.JungleBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.APPLE)));
    public static final RegistryObject<Item> acacia_powder_snow_stew = items.register("acacia_powder_snow_stew", () -> new CustomSoupItem.AcaciaBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.APPLE)));
    public static final RegistryObject<Item> dark_oak_powder_snow_stew = items.register("dark_oak_powder_snow_stew", () -> new CustomSoupItem.DarkOakBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.APPLE)));
    public static final RegistryObject<Item> crimson_powder_snow_stew = items.register("crimson_powder_snow_stew", () -> new CustomSoupItem.CrimsonBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.APPLE)));
    public static final RegistryObject<Item> warped_powder_snow_stew = items.register("warped_powder_snow_stew", () -> new CustomSoupItem.WarpedBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.APPLE)));
    public static final RegistryObject<Item> painting_powder_snow_stew = items.register("painting_powder_snow_stew", () -> new CustomSoupItem.PaintingBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.APPLE)));
    public static final RegistryObject<Item> ender_powder_snow_stew = items.register("ender_powder_snow_stew", () -> new CustomSoupItem.EnderBowl(new Item.Properties().maxStackSize(1).group(VariantTab.variant).food(Foods.APPLE)));

}
