@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.junethewoods.variants.items;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;