package com.junethewoods.variants.item;

import com.junethewoods.variants.Variants;
import com.junethewoods.variants.block.VSBlocks;
import com.junethewoods.variants.entity.VSEntities;
import com.junethewoods.variants.entity.custom.VSBoat;
import com.junethewoods.variants.item.custom.*;
import com.junethewoods.variants.item.custom.food.*;
import com.junethewoods.variants.sound.VSSounds;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.world.entity.vehicle.AbstractMinecart;
import net.minecraft.world.food.Foods;
import net.minecraft.world.item.*;
import net.minecraft.world.level.material.Fluids;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

public class VSItems {
    public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(Variants.MOD_ID);

    // Blocks
    public static final DeferredItem<BlockItem> PLAIN_BIRCH_BOOKSHELF = ITEMS.register("plain_birch_bookshelf", () -> new CompatBlockItem(VSBlocks.PLAIN_BIRCH_BOOKSHELF.get(), new Item.Properties(), "Fabricio2010's Pack"));
    public static final DeferredItem<BlockItem> PAINTING_LOG = ITEMS.register("painting_log", () -> new BlockItem(VSBlocks.PAINTING_LOG.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_WOOD = ITEMS.register("painting_wood", () -> new BlockItem(VSBlocks.PAINTING_WOOD.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> STRIPPED_PAINTING_LOG = ITEMS.register("stripped_painting_log", () -> new BlockItem(VSBlocks.STRIPPED_PAINTING_LOG.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> STRIPPED_PAINTING_WOOD = ITEMS.register("stripped_painting_wood", () -> new BlockItem(VSBlocks.STRIPPED_PAINTING_WOOD.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_LEAVES = ITEMS.register("painting_leaves", () -> new BlockItem(VSBlocks.PAINTING_LEAVES.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_PLANKS = ITEMS.register("painting_planks", () -> new BlockItem(VSBlocks.PAINTING_PLANKS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_STAIRS = ITEMS.register("painting_stairs", () -> new BlockItem(VSBlocks.PAINTING_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_SLAB = ITEMS.register("painting_slab", () -> new BlockItem(VSBlocks.PAINTING_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_FENCE = ITEMS.register("painting_fence", () -> new BlockItem(VSBlocks.PAINTING_FENCE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_FENCE_GATE = ITEMS.register("painting_fence_gate", () -> new BlockItem(VSBlocks.PAINTING_FENCE_GATE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_PRESSURE_PLATE = ITEMS.register("painting_pressure_plate", () -> new BlockItem(VSBlocks.PAINTING_PRESSURE_PLATE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_BUTTON = ITEMS.register("painting_button", () -> new BlockItem(VSBlocks.PAINTING_BUTTON.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_TRAPDOOR = ITEMS.register("painting_trapdoor", () -> new BlockItem(VSBlocks.PAINTING_TRAPDOOR.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_TRAPDOOR_ALBAN = ITEMS.register("alban_trapdoor", () -> new BlockItem(VSBlocks.PAINTING_TRAPDOOR_ALBAN.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_TRAPDOOR_AZTEC = ITEMS.register("aztec_trapdoor", () -> new BlockItem(VSBlocks.PAINTING_TRAPDOOR_AZTEC.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_TRAPDOOR_AZTEC2 = ITEMS.register("aztec2_trapdoor", () -> new BlockItem(VSBlocks.PAINTING_TRAPDOOR_AZTEC2.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_TRAPDOOR_BOMB = ITEMS.register("bomb_trapdoor", () -> new BlockItem(VSBlocks.PAINTING_TRAPDOOR_BOMB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_TRAPDOOR_KEBAB = ITEMS.register("kebab_trapdoor", () -> new BlockItem(VSBlocks.PAINTING_TRAPDOOR_KEBAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_TRAPDOOR_PLANT = ITEMS.register("plant_trapdoor", () -> new BlockItem(VSBlocks.PAINTING_TRAPDOOR_PLANT.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_TRAPDOOR_WASTELAND = ITEMS.register("wasteland_trapdoor", () -> new BlockItem(VSBlocks.PAINTING_TRAPDOOR_WASTELAND.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_DOOR = ITEMS.register("painting_door", () -> new BlockItem(VSBlocks.PAINTING_DOOR.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_DOOR_WANDERER = ITEMS.register("wanderer_door", () -> new BlockItem(VSBlocks.PAINTING_DOOR_WANDERER.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_DOOR_GRAHAM = ITEMS.register("graham_door", () -> new BlockItem(VSBlocks.PAINTING_DOOR_GRAHAM.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_DOOR_FIRST = ITEMS.register("first_door", () -> new CompatBlockItem(VSBlocks.PAINTING_DOOR_FIRST.get(), new Item.Properties(), "Fabricio2010's Pack"));
    public static final DeferredItem<BlockItem> PAINTING_SIGN = ITEMS.register("painting_sign", () -> new SignItem(new Item.Properties().stacksTo(16), VSBlocks.PAINTING_SIGN.get(), VSBlocks.PAINTING_WALL_SIGN.get()));
    public static final DeferredItem<BlockItem> ENDERWOOD_STEM = ITEMS.register("ender_stem", () -> new BlockItem(VSBlocks.ENDERWOOD_STEM.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ENDERWOOD_HYPHAE = ITEMS.register("ender_hyphae", () -> new BlockItem(VSBlocks.ENDERWOOD_HYPHAE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> STRIPPED_ENDERWOOD_STEM = ITEMS.register("stripped_ender_stem", () -> new BlockItem(VSBlocks.STRIPPED_ENDERWOOD_STEM.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> STRIPPED_ENDERWOOD_HYPHAE = ITEMS.register("stripped_ender_hyphae", () -> new BlockItem(VSBlocks.STRIPPED_ENDERWOOD_HYPHAE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ENDER_WART_BLOCK = ITEMS.register("ender_wart_block", () -> new BlockItem(VSBlocks.ENDER_WART_BLOCK.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ENDER_NYLIUM = ITEMS.register("ender_nylium", () -> new BlockItem(VSBlocks.ENDER_NYLIUM.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ENDER_FARMLAND = ITEMS.register("ender_farmland", () -> new BlockItem(VSBlocks.ENDER_FARMLAND.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ENDERWOOD_PLANKS = ITEMS.register("ender_planks", () -> new BlockItem(VSBlocks.ENDERWOOD_PLANKS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ENDERWOOD_BOOKSHELF = ITEMS.register("ender_bookshelf", () -> new BlockItem(VSBlocks.ENDERWOOD_BOOKSHELF.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ENDERWOOD_STAIRS = ITEMS.register("ender_stairs", () -> new BlockItem(VSBlocks.ENDERWOOD_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ENDERWOOD_SLAB = ITEMS.register("ender_slab", () -> new BlockItem(VSBlocks.ENDERWOOD_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ENDERWOOD_FENCE = ITEMS.register("ender_fence", () -> new BlockItem(VSBlocks.ENDERWOOD_FENCE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ENDERWOOD_FENCE_GATE = ITEMS.register("ender_fence_gate", () -> new BlockItem(VSBlocks.ENDERWOOD_FENCE_GATE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ENDERWOOD_PRESSURE_PLATE = ITEMS.register("ender_pressure_plate", () -> new BlockItem(VSBlocks.ENDERWOOD_PRESSURE_PLATE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ENDERWOOD_BUTTON = ITEMS.register("ender_button", () -> new BlockItem(VSBlocks.ENDERWOOD_BUTTON.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ENDERWOOD_TRAPDOOR = ITEMS.register("ender_trapdoor", () -> new BlockItem(VSBlocks.ENDERWOOD_TRAPDOOR.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ENDERWOOD_DOOR = ITEMS.register("ender_door", () -> new BlockItem(VSBlocks.ENDERWOOD_DOOR.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ENDERWOOD_SIGN = ITEMS.register("ender_sign", () -> new SignItem(new Item.Properties().stacksTo(16), VSBlocks.ENDERWOOD_SIGN.get(), VSBlocks.ENDERWOOD_WALL_SIGN.get()));
    public static final DeferredItem<BlockItem> ELDER_SEA_LANTERN = ITEMS.register("elder_sea_lantern", () -> new BlockItem(VSBlocks.ELDER_SEA_LANTERN.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ELDER_PRISMARINE = ITEMS.register("elder_prismarine", () -> new BlockItem(VSBlocks.ELDER_PRISMARINE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ELDER_PRISMARINE_STAIRS = ITEMS.register("elder_prismarine_stairs", () -> new BlockItem(VSBlocks.ELDER_PRISMARINE_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ELDER_PRISMARINE_SLAB = ITEMS.register("elder_prismarine_slab", () -> new BlockItem(VSBlocks.ELDER_PRISMARINE_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ELDER_PRISMARINE_WALL = ITEMS.register("elder_prismarine_wall", () -> new BlockItem(VSBlocks.ELDER_PRISMARINE_WALL.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ELDER_PRISMARINE_BRICKS = ITEMS.register("elder_prismarine_bricks", () -> new BlockItem(VSBlocks.ELDER_PRISMARINE_BRICKS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ELDER_PRISMARINE_BRICK_STAIRS = ITEMS.register("elder_prismarine_brick_stairs", () -> new BlockItem(VSBlocks.ELDER_PRISMARINE_BRICK_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ELDER_PRISMARINE_BRICK_SLAB = ITEMS.register("elder_prismarine_brick_slab", () -> new BlockItem(VSBlocks.ELDER_PRISMARINE_BRICK_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> DARK_ELDER_PRISMARINE = ITEMS.register("dark_elder_prismarine", () -> new BlockItem(VSBlocks.DARK_ELDER_PRISMARINE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> DARK_ELDER_PRISMARINE_STAIRS = ITEMS.register("dark_elder_prismarine_stairs", () -> new BlockItem(VSBlocks.DARK_ELDER_PRISMARINE_STAIRS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> DARK_ELDER_PRISMARINE_SLAB = ITEMS.register("dark_elder_prismarine_slab", () -> new BlockItem(VSBlocks.DARK_ELDER_PRISMARINE_SLAB.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CHISELED_END_STONE_BRICKS = ITEMS.register("chiseled_end_stone_bricks", () -> new BlockItem(VSBlocks.CHISELED_END_STONE_BRICKS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> INFESTED_CHISELED_END_STONE_BRICKS = ITEMS.register("infested_chiseled_end_stone_bricks", () -> new BlockItem(VSBlocks.INFESTED_CHISELED_END_STONE_BRICKS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> CHISELED_PURPUR_BLOCK = ITEMS.register("chiseled_purpur_block", () -> new BlockItem(VSBlocks.CHISELED_PURPUR_BLOCK.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> INFESTED_CHISELED_PURPUR_BLOCK = ITEMS.register("infested_chiseled_purpur_block", () -> new BlockItem(VSBlocks.INFESTED_CHISELED_PURPUR_BLOCK.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> RED_NETHER_BRICK_FENCE = ITEMS.register("red_nether_brick_fence", () -> new BlockItem(VSBlocks.RED_NETHER_BRICK_FENCE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> WITHER_BONE_BLOCK = ITEMS.register("wither_bone_block", () -> new BlockItem(VSBlocks.WITHER_BONE_BLOCK.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> RAW_DEBRIS_BLOCK = ITEMS.register("raw_debris_block", () -> new BlockItem(VSBlocks.RAW_DEBRIS_BLOCK.get(), new Item.Properties().fireResistant()));
    public static final DeferredItem<BlockItem> QUARTZ_ORE = ITEMS.register("quartz_ore", () -> new BlockItem(VSBlocks.QUARTZ_ORE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> DEEPSLATE_QUARTZ_ORE = ITEMS.register("deepslate_quartz_ore", () -> new BlockItem(VSBlocks.DEEPSLATE_QUARTZ_ORE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> END_QUARTZ_ORE = ITEMS.register("end_quartz_ore", () -> new BlockItem(VSBlocks.END_QUARTZ_ORE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> GOLDEN_CAULDRON = ITEMS.register("gold_cauldron", () -> new BlockItem(VSBlocks.GOLDEN_CAULDRON.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> GOLDEN_BEACON = ITEMS.register("gold_beacon", () -> new BlockItem(VSBlocks.GOLDEN_BEACON.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final DeferredItem<BlockItem> DIAMOND_BELL = ITEMS.register("diamond_bell", () -> new BlockItem(VSBlocks.DIAMOND_BELL.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> NETHERRACK_LEVER = ITEMS.register("netherrack_lever", () -> new BlockItem(VSBlocks.NETHERRACK_LEVER.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> END_STONE_LEVER = ITEMS.register("end_stone_lever", () -> new BlockItem(VSBlocks.END_STONE_LEVER.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> GLOW_BLACK_WOOL = ITEMS.register("glow_black_wool", () -> new BlockItem(VSBlocks.GLOW_BLACK_WOOL.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> GLOW_BLACK_CARPET = ITEMS.register("glow_black_carpet", () -> new BlockItem(VSBlocks.GLOW_BLACK_CARPET.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> GLOW_BLACK_BED = ITEMS.register("glow_black_bed", () -> new BedItem(VSBlocks.GLOW_BLACK_BED.get(), new Item.Properties().stacksTo(1)));
    public static final DeferredItem<BlockItem> GLOW_BLACK_STAINED_GLASS = ITEMS.register("glow_black_stained_glass", () -> new BlockItem(VSBlocks.GLOW_BLACK_STAINED_GLASS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> GLOW_BLACK_STAINED_GLASS_PANE = ITEMS.register("glow_black_stained_glass_pane", () -> new BlockItem(VSBlocks.GLOW_BLACK_STAINED_GLASS_PANE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> QUARTZ_GLASS = ITEMS.register("quartz_glass", () -> new BlockItem(VSBlocks.QUARTZ_GLASS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> QUARTZ_GLASS_PANE = ITEMS.register("quartz_glass_pane", () -> new BlockItem(VSBlocks.QUARTZ_GLASS_PANE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> QUARTZ_BARS = ITEMS.register("quartz_bars", () -> new BlockItem(VSBlocks.QUARTZ_BARS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> QUARTZ_CHAIN = ITEMS.register("quartz_chain", () -> new BlockItem(VSBlocks.QUARTZ_CHAIN.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> GOLDEN_CHAIN = ITEMS.register("golden_chain", () -> new BlockItem(VSBlocks.GOLDEN_CHAIN.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> DIAMOND_CHAIN = ITEMS.register("diamond_chain", () -> new BlockItem(VSBlocks.DIAMOND_CHAIN.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> EMERALD_CHAIN = ITEMS.register("emerald_chain", () -> new BlockItem(VSBlocks.EMERALD_CHAIN.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> POTTED_SUGAR_CANE = ITEMS.register("potted_sugar_cane", () -> new BlockItem(VSBlocks.POTTED_SUGAR_CANE.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> POTTED_GLOW_BLACK_TULIP = ITEMS.register("potted_glow_black_tulip", () -> new BlockItem(VSBlocks.POTTED_GLOW_BLACK_TULIP.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> POTTED_SUNNY_FLOWER = ITEMS.register("potted_sunny_flower", () -> new BlockItem(VSBlocks.POTTED_SUNNY_FLOWER.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> POTTED_PAINTING_SAPLING = ITEMS.register("potted_painting_sapling", () -> new BlockItem(VSBlocks.POTTED_PAINTING_SAPLING.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> GOLDEN_CARROTS = ITEMS.register("golden_carrots", () -> new BlockItem(VSBlocks.GOLDEN_CARROTS.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredItem<BlockItem> GLOW_BLACK_TULIP = ITEMS.register("glow_black_tulip", () -> new BlockItem(VSBlocks.GLOW_BLACK_TULIP.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> SUNNY_FLOWER = ITEMS.register("sunny_flower", () -> new BlockItem(VSBlocks.SUNNY_FLOWER.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> GLOW_BERRY_BUSH = ITEMS.register("glow_berry_bush", () -> new BlockItem(VSBlocks.GLOW_BERRY_BUSH.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> PAINTING_SAPLING = ITEMS.register("painting_sapling", () -> new BlockItem(VSBlocks.PAINTING_SAPLING.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ENDER_ROOTS = ITEMS.register("ender_roots", () -> new BlockItem(VSBlocks.ENDER_ROOTS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> END_SPROUTS = ITEMS.register("ender_sprouts", () -> new BlockItem(VSBlocks.END_SPROUTS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ENDER_FUNGUS = ITEMS.register("ender_fungus", () -> new BlockItem(VSBlocks.ENDER_FUNGUS.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> WARPING_VINES = ITEMS.register("warping_vines", () -> new BlockItem(VSBlocks.WARPING_VINES.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> WARPED_WART = ITEMS.register("warped_wart", () -> new ItemNameBlockItem(VSBlocks.WARPED_WART.get(), new Item.Properties()));
    public static final DeferredItem<BlockItem> ENDER_WART = ITEMS.register("ender_wart", () -> new ItemNameBlockItem(VSBlocks.ENDER_WART.get(), new Item.Properties()));

    // Items
    public static final DeferredItem<Item> WHITE_SHULKER_SHELL = ITEMS.register("white_shulker_shell", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> INNO_SHULKER_SHELL = ITEMS.register("inno_shulker_shell", () -> new CompatItem(new Item.Properties(), "F10 Elements"));
    public static final DeferredItem<Item> ORANGE_SHULKER_SHELL = ITEMS.register("orange_shulker_shell", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> MAGENTA_SHULKER_SHELL = ITEMS.register("magenta_shulker_shell", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> LIGHT_BLUE_SHULKER_SHELL = ITEMS.register("light_blue_shulker_shell", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> GLOW_BLACK_SHULKER_SHELL = ITEMS.register("glow_black_shulker_shell", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> YELLOW_SHULKER_SHELL = ITEMS.register("yellow_shulker_shell", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> LIME_SHULKER_SHELL = ITEMS.register("lime_shulker_shell", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> PINK_SHULKER_SHELL = ITEMS.register("pink_shulker_shell", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> GRAY_SHULKER_SHELL = ITEMS.register("gray_shulker_shell", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> LIGHT_GRAY_SHULKER_SHELL = ITEMS.register("light_gray_shulker_shell", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> CYAN_SHULKER_SHELL = ITEMS.register("cyan_shulker_shell", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> PURPLE_SHULKER_SHELL = ITEMS.register("purple_shulker_shell", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> BLUE_SHULKER_SHELL = ITEMS.register("blue_shulker_shell", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> BROWN_SHULKER_SHELL = ITEMS.register("brown_shulker_shell", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> GREEN_SHULKER_SHELL = ITEMS.register("green_shulker_shell", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RED_SHULKER_SHELL = ITEMS.register("red_shulker_shell", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> BLACK_SHULKER_SHELL = ITEMS.register("black_shulker_shell", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> MUSIC_DISC_DOG = ITEMS.register("music_disc_dog", () -> new RecordItem(2, VSSounds.MUSIC_DISC_DOG, new Item.Properties().rarity(Rarity.RARE).stacksTo(1), 2452));
    public static final DeferredItem<Item> SPAWNER_MINECART = ITEMS.register("spawner_minecart", () -> new MinecartItem(AbstractMinecart.Type.SPAWNER, new Item.Properties().rarity(Rarity.UNCOMMON).stacksTo(1)));
//    public static final DeferredItem<Item> SOUL_LAVA_BUCKET = ITEMS.register("soul_lava_bucket", () -> new SoulLavaBucketItem(new Item.Properties().stacksTo(1).craftRemainder(Items.BUCKET)));
    public static final DeferredItem<Item> FISH_BUCKET = ITEMS.register("old_cod_bucket", () -> new MobBucketItem(VSEntities.FISH, () -> Fluids.WATER, () -> SoundEvents.BUCKET_FILL_FISH, new Item.Properties().stacksTo(1).craftRemainder(Items.BUCKET)));
    public static final DeferredItem<Item> FISH_SPAWN_EGG = ITEMS.register("old_cod_spawn_egg", () -> new DeferredSpawnEggItem(VSEntities.FISH, 0x6B9F93, 0xADBEDB, new Item.Properties()));
    public static final DeferredItem<Item> FUNGI_STEW = ITEMS.register("fungi_stew", () -> new BowlFoodItem(new Item.Properties().stacksTo(1).food(Foods.MUSHROOM_STEW)));
    public static final DeferredItem<Item> END_FUNGI_STEW = ITEMS.register("end_fungi_stew", () -> new BowlFoodItem(new Item.Properties().stacksTo(1).food(Foods.MUSHROOM_STEW)));
    public static final DeferredItem<Item> PAINTING_BOAT = ITEMS.register("painting_boat", () -> new VSBoatItem(false, VSBoat.Type.PAINTING, new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> CRIMSON_BOAT = ITEMS.register("crimson_boat", () -> new VSBoatItem(false, VSBoat.Type.CRIMSON, new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> WARPED_BOAT = ITEMS.register("warped_boat", () -> new VSBoatItem(false, VSBoat.Type.WARPED, new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> SPLASH_EXPERIENCE_BOTTLE = ITEMS.register("splash_experience_bottle", () -> new ExperienceBottleItem(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredItem<Item> LINGERING_EXPERIENCE_BOTTLE = ITEMS.register("lingering_experience_bottle", () -> new ExperienceBottleItem(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final DeferredItem<Item> SPLASH_DRAGON_BREATH = ITEMS.register("splash_dragon_breath", () -> new Item(new Item.Properties().craftRemainder(Items.SPLASH_POTION).rarity(Rarity.UNCOMMON)));
    public static final DeferredItem<Item> LINGERING_DRAGON_BREATH = ITEMS.register("lingering_dragon_breath", () -> new Item(new Item.Properties().craftRemainder(Items.LINGERING_POTION).rarity(Rarity.UNCOMMON)));
    public static final DeferredItem<Item> SPLASH_GLASS_BOTTLE = ITEMS.register("splash_glass_bottle", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> LINGERING_GLASS_BOTTLE = ITEMS.register("lingering_glass_bottle", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> LAVA_BOTTLE = ITEMS.register("lava_glass_bottle", () -> new LavaBottleItem(new Item.Properties().stacksTo(8).craftRemainder(Items.GLASS_BOTTLE)));
    public static final DeferredItem<Item> SOUL_LAVA_BOTTLE = ITEMS.register("soul_lava_bottle", () -> new LavaBottleItem(new Item.Properties().stacksTo(8).craftRemainder(Items.GLASS_BOTTLE)));
    public static final DeferredItem<Item> MILK_BOTTLE = ITEMS.register("milk_glass_bottle", () -> new MilkBottleItem(new Item.Properties().stacksTo(8).craftRemainder(Items.GLASS_BOTTLE)));
    public static final DeferredItem<Item> POWDER_SNOW_BOTTLE = ITEMS.register("powder_snow_bottle", () -> new PowderSnowBottleItem(new Item.Properties().stacksTo(8).craftRemainder(Items.GLASS_BOTTLE)));
    public static final DeferredItem<Item> SPLASH_SOPHIE_POTION = ITEMS.register("splash_soph_potion", () -> new SophiePotionItem(new Item.Properties().food(VSFoods.SOPHIE_POTION), "Edits"));
    public static final DeferredItem<Item> STYLISED_POT = ITEMS.register("stylised_pot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> REDSTONE_POT = ITEMS.register("redstone_pot", () -> new StylisedPotItem(new Item.Properties().stacksTo(16), PoisoningTypes.REDSTONE, 10));
    public static final DeferredItem<Item> BLUESTONE_POT = ITEMS.register("bluestone_pot", () -> new StylisedPotItem(new Item.Properties().stacksTo(16), "Fabricio2010's Pack", PoisoningTypes.BLUESTONE, 10));
    public static final DeferredItem<Item> GLOWSTONE_POT = ITEMS.register("glowstone_pot", () -> new StylisedPotItem(new Item.Properties().stacksTo(16), PoisoningTypes.GLOWSTONE, 10));
    public static final DeferredItem<Item> GUNPOWDER_POT = ITEMS.register("gunpowder_pot", () -> new StylisedPotItem(new Item.Properties().stacksTo(16), PoisoningTypes.GUNPOWDER, 10));
    public static final DeferredItem<Item> EXPLOSIVE_BLEND_POT = ITEMS.register("creeper_powder_pot", () -> new StylisedPotItem(new Item.Properties().stacksTo(16), "Creeper Edits", PoisoningTypes.CREEPER_POWDER, 10));
    public static final DeferredItem<Item> SUGAR_POT = ITEMS.register("sugar_pot", () -> new SugarPotItem(new Item.Properties().stacksTo(16)));
    public static final DeferredItem<Item> SWEET_BERRY_POT = ITEMS.register("sweet_berry_pot", () -> new Item(new Item.Properties().stacksTo(16).food(VSFoods.BERRY_POTS).craftRemainder(VSItems.STYLISED_POT.get())));
    public static final DeferredItem<Item> GLOW_BERRY_POT = ITEMS.register("glow_berry_pot", () -> new Item(new Item.Properties().stacksTo(16).food(VSFoods.BERRY_POTS).craftRemainder(VSItems.STYLISED_POT.get())));
    public static final DeferredItem<Item> HONEY_BALL = ITEMS.register("honey_ball", () -> new HoneyBallItem(new Item.Properties().food(Foods.HONEY_BOTTLE)));
    public static final DeferredItem<Item> RAW_FISH = ITEMS.register("old_cod", () -> new Item(new Item.Properties().food(Foods.COD)));
    public static final DeferredItem<Item> COOKED_FISH = ITEMS.register("old_cooked_cod", () -> new Item(new Item.Properties().food(Foods.COOKED_COD)));
    public static final DeferredItem<Item> RAW_DEBRIS = ITEMS.register("raw_debris", () -> new Item(new Item.Properties().fireResistant()));
    public static final DeferredItem<Item> OAK_STICK = ITEMS.register("oak_stick", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> SPRUCE_STICK = ITEMS.register("spruce_stick", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> BIRCH_STICK = ITEMS.register("birch_stick", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> JUNGLE_STICK = ITEMS.register("jungle_stick", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> ACACIA_STICK = ITEMS.register("acacia_stick", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> DARK_OAK_STICK = ITEMS.register("dark_oak_stick", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> PAINTING_STICK = ITEMS.register("painting_stick", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> CRIMSON_STICK = ITEMS.register("crimson_stick", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> WARPED_STICK = ITEMS.register("warped_stick", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> ENDERWOOD_STICK = ITEMS.register("ender_stick", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> NETHERITE_ROD = ITEMS.register("netherite_rod", () -> new Item(new Item.Properties().fireResistant()));
    public static final DeferredItem<Item> OAK_BOWL = ITEMS.register("oak_bowl", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> SPRUCE_BOWL = ITEMS.register("spruce_bowl", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> BIRCH_BOWL = ITEMS.register("birch_bowl", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> JUNGLE_BOWL = ITEMS.register("jungle_bowl", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> ACACIA_BOWL = ITEMS.register("acacia_bowl", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> DARK_OAK_BOWL = ITEMS.register("dark_oak_bowl", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> PAINTING_BOWL = ITEMS.register("painting_bowl", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> CRIMSON_BOWL = ITEMS.register("crimson_bowl", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> WARPED_BOWL = ITEMS.register("warped_bowl", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> ENDERWOOD_BOWL = ITEMS.register("ender_bowl", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> SOUL_BLAZE_ROD = ITEMS.register("soul_rod", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> SOUL_BLAZE_POWDER = ITEMS.register("soul_powder", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> SOUL_O_CHARGE = ITEMS.register("soul_charge", () -> new FireChargeItem(new Item.Properties()));
    public static final DeferredItem<Item> RED_NETHER_BRICK = ITEMS.register("red_nether_brick", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> EXPOSED_COPPER_INGOT = ITEMS.register("exposed_copper_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> WEATHERED_COPPER_INGOT = ITEMS.register("weathered_copper_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> OXIDIZED_COPPER_INGOT = ITEMS.register("oxidized_copper_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> QUARTZ_SHARD = ITEMS.register("quartz_nugget", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> PURPLE_IRON_NUGGET = ITEMS.register("purple_nugget", () -> new CompatItem(new Item.Properties(), "Edits"));
    public static final DeferredItem<Item> GLOW_BLACK_DYE = ITEMS.register("glow_black_dye", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> ELDER_PRISMARINE_SHARD = ITEMS.register("elder_prismarine_shard", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> ELDER_PRISMARINE_CRYSTALS = ITEMS.register("elder_prismarine_crystals", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> WITHER_BONE = ITEMS.register("wither_bone", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> WITHER_BONE_MEAL = ITEMS.register("wither_bone_meal", () -> new BoneMealItem(new Item.Properties()));
    public static final DeferredItem<Item> ENCHANTED_KNOWLEDGE_BOOK = ITEMS.register("enchanted_knowledge_book", () -> new EnchantedKnowledgeBookItem(new Item.Properties().rarity(Rarity.UNCOMMON).stacksTo(1)));
}
