package com.junethewoods.variants.item;

import com.junethewoods.variants.Variants;
import com.junethewoods.variants.item.custom.tool.*;
import com.junethewoods.variants.item.custom.armor.WoolArmorItem;
import com.junethewoods.variants.util.tab.VSWeaponryTab;
import com.junethewoods.variants.item.tool.VSArmors;
import com.junethewoods.variants.item.tool.VSTools;
import net.minecraft.inventory.EquipmentSlotType;
import net.minecraft.item.*;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class VSWeaponry {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, Variants.MOD_ID);

    public static final RegistryObject<Item> DIORITE_SWORD = ITEMS.register("diorite_sword", () -> new SwordItem(VSTools.DIORITE, 3, -2.4F, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> DIORITE_PICKAXE = ITEMS.register("diorite_pickaxe", () -> new PickaxeItem(VSTools.DIORITE, 1, -2.8F, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> DIORITE_SHOVEL = ITEMS.register("diorite_shovel", () -> new ShovelItem(VSTools.DIORITE, 1.5F, -3f, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> DIORITE_AXE = ITEMS.register("diorite_axe", () -> new AxeItem(VSTools.DIORITE, 7f, -3.2F, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> DIORITE_HOE = ITEMS.register("diorite_hoe", () -> new HoeItem(VSTools.DIORITE, -1, -2f, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> GRANITE_SWORD = ITEMS.register("granite_sword", () -> new SwordItem(VSTools.GRANITE, 3, -2.4F, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> GRANITE_PICKAXE = ITEMS.register("granite_pickaxe", () -> new PickaxeItem(VSTools.GRANITE, 1, -2.8F, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> GRANITE_SHOVEL = ITEMS.register("granite_shovel", () -> new ShovelItem(VSTools.GRANITE, 1.5F, -3f, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> GRANITE_AXE = ITEMS.register("granite_axe", () -> new AxeItem(VSTools.GRANITE, 7f, -3.2F, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> GRANITE_HOE = ITEMS.register("granite_hoe", () -> new HoeItem(VSTools.GRANITE, -1, -2f, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> ANDESITE_SWORD = ITEMS.register("andesite_sword", () -> new SwordItem(VSTools.ANDESITE, 3, -2.4F, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> ANDESITE_PICKAXE = ITEMS.register("andesite_pickaxe", () -> new PickaxeItem(VSTools.ANDESITE, 1, -2.8F, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> ANDESITE_SHOVEL = ITEMS.register("andesite_shovel", () -> new ShovelItem(VSTools.ANDESITE, 1.5F, -3f, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> ANDESITE_AXE = ITEMS.register("andesite_axe", () -> new AxeItem(VSTools.ANDESITE, 7f, -3.2F, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> ANDESITE_HOE = ITEMS.register("andesite_hoe", () -> new HoeItem(VSTools.ANDESITE, -1, -2f, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> END_STONE_SWORD = ITEMS.register("end_stone_sword", () -> new SwordItem(VSTools.END_STONE, 3, -2.4F, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> END_STONE_PICKAXE = ITEMS.register("end_stone_pickaxe", () -> new PickaxeItem(VSTools.END_STONE, 1, -2.8F, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> END_STONE_SHOVEL = ITEMS.register("end_stone_shovel", () -> new ShovelItem(VSTools.END_STONE, 1.5F, -3f, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> END_STONE_AXE = ITEMS.register("end_stone_axe", () -> new AxeItem(VSTools.END_STONE, 7f, -3.2F, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> END_STONE_HOE = ITEMS.register("end_stone_hoe", () -> new HoeItem(VSTools.END_STONE, -1, -2f, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_SWORD = ITEMS.register("quartz_sword", () -> new SwordItem(VSTools.QUARTZ, 3, -2.4F, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_PICKAXE = ITEMS.register("quartz_pickaxe", () -> new PickaxeItem(VSTools.QUARTZ, 1, -2.8F, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_SHOVEL = ITEMS.register("quartz_shovel", () -> new ShovelItem(VSTools.QUARTZ, 1.5F, -3f, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_AXE = ITEMS.register("quartz_axe", () -> new AxeItem(VSTools.QUARTZ, 7f, -3.2F, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_HOE = ITEMS.register("quartz_hoe", () -> new HoeItem(VSTools.QUARTZ, -1, -2f, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> MAGMA_SWORD = ITEMS.register("magma_sword", () -> new MagmaSwordItem(VSTools.MAGMA, 3, -2.4F, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> AMETHYST_SWORD = ITEMS.register("amethyst_sword", () -> new SwordItem(VSTools.AMETHYST, 3, -2.4F, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> COPPER_SWORD = ITEMS.register("copper_sword", () -> new SwordItem(VSTools.COPPER, 3, -2.4F, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> DEBUG_BOW = ITEMS.register("debug_bow", () -> new DebugBowItem(new Item.Properties().durability(3840).tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> REDSTONE_SHEARS = ITEMS.register("redstone_shears", () -> new ShearsItem(new Item.Properties().durability(250).tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> COAL_SHEARS = ITEMS.register("coal_shears", () -> new CoalShearsItem(new Item.Properties().durability(32).tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> COPPER_SHEARS = ITEMS.register("copper_shears", () -> new ShearsItem(new Item.Properties().durability(131).tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> EXPOSED_COPPER_SHEARS = ITEMS.register("exposed_copper_shears", () -> new ShearsItem(new Item.Properties().durability(131).tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> WEATHERED_COPPER_SHEARS = ITEMS.register("weathered_copper_shears", () -> new ShearsItem(new Item.Properties().durability(131).tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> OXIDIZED_COPPER_SHEARS = ITEMS.register("oxidized_copper_shears", () -> new ShearsItem(new Item.Properties().durability(131).tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> AMETHYST_SHEARS = ITEMS.register("amethyst_shears", () -> new ShearsItem(new Item.Properties().durability(450).tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> DIAMOND_SHEARS = ITEMS.register("diamond_shears", () -> new ShearsItem(new Item.Properties().durability(1561).tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> GOLDEN_SHEARS = ITEMS.register("golden_shears", () -> new ShearsItem(new Item.Properties().durability(250).tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> NETHERITE_SHEARS = ITEMS.register("netherite_shears", () -> new ShearsItem(new Item.Properties().durability(2031).fireResistant().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> LAPIS_LAZULI_SHEARS = ITEMS.register("lapis_lazuli_shears", () -> new ShearsItem(new Item.Properties().durability(1671).tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> EMERALD_SHEARS = ITEMS.register("emerald_shears", () -> new ShearsItem(new Item.Properties().durability(1561).tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_SHEARS = ITEMS.register("quartz_shears", () -> new ShearsItem(new Item.Properties().durability(500).tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> RUBY_SHEARS = ITEMS.register("ruby_shears", () -> new ShearsItem(new Item.Properties().durability(1871).tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> PLASTEEL_SHEARS = ITEMS.register("plasteel_shears", () -> new CompatShearsItem(new Item.Properties().durability(450).tab(VSWeaponryTab.TAB), "Rimcraft"));
    public static final RegistryObject<Item> DIAEMERALD_SHEARS = ITEMS.register("diaemerald_shears", () -> new CompatShearsItem(new Item.Properties().durability(725).tab(VSWeaponryTab.TAB), "My Other Stuff (Others)"));
    public static final RegistryObject<Item> CRYSTAL_SHEARS = ITEMS.register("crystal_shears", () -> new CompatShearsItem(new Item.Properties().durability(861).tab(VSWeaponryTab.TAB), "My Other Stuff (Others)"));
    public static final RegistryObject<Item> LIGHT_MAGENTA_SHEARS = ITEMS.register("light_magenta_shears", () -> new CompatShearsItem(new Item.Properties().durability(861).tab(VSWeaponryTab.TAB), "My Other Stuff (Others)"));
    public static final RegistryObject<Item> ALAN_AI_SHEARS = ITEMS.register("alan_ai_shears", () -> new CompatShearsItem(new Item.Properties().durability(600).tab(VSWeaponryTab.TAB), "My Other Stuff (Others)"));
    public static final RegistryObject<Item> ALICE_AI_SHEARS = ITEMS.register("alice_ai_shears", () -> new CompatShearsItem(new Item.Properties().durability(600).tab(VSWeaponryTab.TAB), "My Other Stuff (Others)"));
    public static final RegistryObject<Item> INNO_AI_SHEARS = ITEMS.register("inno_ai_shears", () -> new CompatShearsItem(new Item.Properties().durability(600).tab(VSWeaponryTab.TAB), "My Other Stuff (Others)"));
    public static final RegistryObject<Item> NICOLAS_AI_SHEARS = ITEMS.register("nicolas_ai_shears", () -> new CompatShearsItem(new Item.Properties().durability(600).tab(VSWeaponryTab.TAB), "My Other Stuff (Others)"));
    public static final RegistryObject<Item> QUARTZ_HELMET = ITEMS.register("quartz_helmet", () -> new ArmorItem(VSArmors.QUARTZ, EquipmentSlotType.HEAD, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_CHESTPLATE = ITEMS.register("quartz_chestplate", () -> new ArmorItem(VSArmors.QUARTZ, EquipmentSlotType.CHEST, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_LEGGINGS = ITEMS.register("quartz_leggings", () -> new ArmorItem(VSArmors.QUARTZ, EquipmentSlotType.LEGS, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_BOOTS = ITEMS.register("quartz_boots", () -> new ArmorItem(VSArmors.QUARTZ, EquipmentSlotType.FEET, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_HORSE_ARMOR = ITEMS.register("quartz_horse_armor", () -> new HorseArmorItem(9, Variants.resourceLoc("textures/entity/horse/armor/horse_armor_quartz.png"), new Item.Properties().stacksTo(1).tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> EMERALD_HELMET = ITEMS.register("emerald_helmet", () -> new ArmorItem(VSArmors.EMERALD, EquipmentSlotType.HEAD, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> EMERALD_CHESTPLATE = ITEMS.register("emerald_chestplate", () -> new ArmorItem(VSArmors.EMERALD, EquipmentSlotType.CHEST, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> EMERALD_LEGGINGS = ITEMS.register("emerald_leggings", () -> new ArmorItem(VSArmors.EMERALD, EquipmentSlotType.LEGS, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> EMERALD_BOOTS = ITEMS.register("emerald_boots", () -> new ArmorItem(VSArmors.EMERALD, EquipmentSlotType.FEET, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> EMPTY_ARMOR_SLOT_HELMET = ITEMS.register("empty_armor_slot_helmet", () -> new ArmorItem(VSArmors.EMPTY_SLOT, EquipmentSlotType.HEAD, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> EMPTY_ARMOR_SLOT_CHESTPLATE = ITEMS.register("empty_armor_slot_chestplate", () -> new ArmorItem(VSArmors.EMPTY_SLOT, EquipmentSlotType.CHEST, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> EMPTY_ARMOR_SLOT_LEGGINGS = ITEMS.register("empty_armor_slot_leggings", () -> new ArmorItem(VSArmors.EMPTY_SLOT, EquipmentSlotType.LEGS, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> EMPTY_ARMOR_SLOT_BOOTS = ITEMS.register("empty_armor_slot_boots", () -> new ArmorItem(VSArmors.EMPTY_SLOT, EquipmentSlotType.FEET, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> EMPTY_ARMOR_SLOT_SHIELD = ITEMS.register("empty_armor_slot_shield", () -> new VSShieldItem(new Item.Properties().durability(496).tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> COPPER_CHESTPLATE = ITEMS.register("copper_chestplate", () -> new ArmorItem(VSArmors.COPPER, EquipmentSlotType.CHEST, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> PHANTOM_MEMBRANE_TUNIC = ITEMS.register("phantom_membrane_sweatchest", () -> new ArmorItem(VSArmors.PHANTOM_MEMBRANE, EquipmentSlotType.CHEST, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> RABBIT_HIDE_TUNIC = ITEMS.register("rabbit_hide_sweatchest", () -> new ArmorItem(VSArmors.RABBIT_HIDE, EquipmentSlotType.CHEST, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> WOOL_SWEATER = ITEMS.register("wool_sweatchest", () -> new WoolArmorItem(VSArmors.WOOL, EquipmentSlotType.CHEST, new Item.Properties().tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> IRON_SPYGLASS = ITEMS.register("iron_spyglass", () -> new SpyglassItem(new Item.Properties().stacksTo(1).tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> DIAMOND_SPYGLASS = ITEMS.register("diamond_spyglass", () -> new SpyglassItem(new Item.Properties().stacksTo(1).tab(VSWeaponryTab.TAB)));
    public static final RegistryObject<Item> NETHERITE_SPYGLASS = ITEMS.register("netherite_spyglass", () -> new SpyglassItem(new Item.Properties().stacksTo(1).fireResistant().tab(VSWeaponryTab.TAB)));
}
