package com.junethewoods.variants.item;

import com.junethewoods.variants.Variants;
import com.junethewoods.variants.item.custom.tool.*;
import com.junethewoods.variants.item.custom.armor.WoolArmorItem;
import com.junethewoods.variants.item.tool.VSArmors;
import com.junethewoods.variants.item.tool.VSTools;
import net.minecraft.world.item.*;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

public class VSWeaponry {
    public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(Variants.MOD_ID);

    public static final DeferredItem<Item> DIORITE_SWORD = ITEMS.register("diorite_sword", () -> new SwordItem(VSTools.DIORITE, 3, -2.4F, new Item.Properties()));
    public static final DeferredItem<Item> DIORITE_PICKAXE = ITEMS.register("diorite_pickaxe", () -> new PickaxeItem(VSTools.DIORITE, 1, -2.8F, new Item.Properties()));
    public static final DeferredItem<Item> DIORITE_SHOVEL = ITEMS.register("diorite_shovel", () -> new ShovelItem(VSTools.DIORITE, 1.5F, -3f, new Item.Properties()));
    public static final DeferredItem<Item> DIORITE_AXE = ITEMS.register("diorite_axe", () -> new AxeItem(VSTools.DIORITE, 7f, -3.2F, new Item.Properties()));
    public static final DeferredItem<Item> DIORITE_HOE = ITEMS.register("diorite_hoe", () -> new HoeItem(VSTools.DIORITE, -1, -2f, new Item.Properties()));
    public static final DeferredItem<Item> GRANITE_SWORD = ITEMS.register("granite_sword", () -> new SwordItem(VSTools.GRANITE, 3, -2.4F, new Item.Properties()));
    public static final DeferredItem<Item> GRANITE_PICKAXE = ITEMS.register("granite_pickaxe", () -> new PickaxeItem(VSTools.GRANITE, 1, -2.8F, new Item.Properties()));
    public static final DeferredItem<Item> GRANITE_SHOVEL = ITEMS.register("granite_shovel", () -> new ShovelItem(VSTools.GRANITE, 1.5F, -3f, new Item.Properties()));
    public static final DeferredItem<Item> GRANITE_AXE = ITEMS.register("granite_axe", () -> new AxeItem(VSTools.GRANITE, 7f, -3.2F, new Item.Properties()));
    public static final DeferredItem<Item> GRANITE_HOE = ITEMS.register("granite_hoe", () -> new HoeItem(VSTools.GRANITE, -1, -2f, new Item.Properties()));
    public static final DeferredItem<Item> ANDESITE_SWORD = ITEMS.register("andesite_sword", () -> new SwordItem(VSTools.ANDESITE, 3, -2.4F, new Item.Properties()));
    public static final DeferredItem<Item> ANDESITE_PICKAXE = ITEMS.register("andesite_pickaxe", () -> new PickaxeItem(VSTools.ANDESITE, 1, -2.8F, new Item.Properties()));
    public static final DeferredItem<Item> ANDESITE_SHOVEL = ITEMS.register("andesite_shovel", () -> new ShovelItem(VSTools.ANDESITE, 1.5F, -3f, new Item.Properties()));
    public static final DeferredItem<Item> ANDESITE_AXE = ITEMS.register("andesite_axe", () -> new AxeItem(VSTools.ANDESITE, 7f, -3.2F, new Item.Properties()));
    public static final DeferredItem<Item> ANDESITE_HOE = ITEMS.register("andesite_hoe", () -> new HoeItem(VSTools.ANDESITE, -1, -2f, new Item.Properties()));
    public static final DeferredItem<Item> END_STONE_SWORD = ITEMS.register("end_stone_sword", () -> new SwordItem(VSTools.END_STONE, 3, -2.4F, new Item.Properties()));
    public static final DeferredItem<Item> END_STONE_PICKAXE = ITEMS.register("end_stone_pickaxe", () -> new PickaxeItem(VSTools.END_STONE, 1, -2.8F, new Item.Properties()));
    public static final DeferredItem<Item> END_STONE_SHOVEL = ITEMS.register("end_stone_shovel", () -> new ShovelItem(VSTools.END_STONE, 1.5F, -3f, new Item.Properties()));
    public static final DeferredItem<Item> END_STONE_AXE = ITEMS.register("end_stone_axe", () -> new AxeItem(VSTools.END_STONE, 7f, -3.2F, new Item.Properties()));
    public static final DeferredItem<Item> END_STONE_HOE = ITEMS.register("end_stone_hoe", () -> new HoeItem(VSTools.END_STONE, -1, -2f, new Item.Properties()));
    public static final DeferredItem<Item> QUARTZ_SWORD = ITEMS.register("quartz_sword", () -> new SwordItem(VSTools.QUARTZ, 3, -2.4F, new Item.Properties()));
    public static final DeferredItem<Item> QUARTZ_PICKAXE = ITEMS.register("quartz_pickaxe", () -> new PickaxeItem(VSTools.QUARTZ, 1, -2.8F, new Item.Properties()));
    public static final DeferredItem<Item> QUARTZ_SHOVEL = ITEMS.register("quartz_shovel", () -> new ShovelItem(VSTools.QUARTZ, 1.5F, -3f, new Item.Properties()));
    public static final DeferredItem<Item> QUARTZ_AXE = ITEMS.register("quartz_axe", () -> new AxeItem(VSTools.QUARTZ, 7f, -3.2F, new Item.Properties()));
    public static final DeferredItem<Item> QUARTZ_HOE = ITEMS.register("quartz_hoe", () -> new HoeItem(VSTools.QUARTZ, -1, -2f, new Item.Properties()));
    public static final DeferredItem<Item> MAGMA_SWORD = ITEMS.register("magma_sword", () -> new MagmaSwordItem(VSTools.MAGMA, 3, -2.4F, new Item.Properties()));
    public static final DeferredItem<Item> AMETHYST_SWORD = ITEMS.register("amethyst_sword", () -> new SwordItem(VSTools.AMETHYST, 3, -2.4F, new Item.Properties()));
    public static final DeferredItem<Item> COPPER_SWORD = ITEMS.register("copper_sword", () -> new SwordItem(VSTools.COPPER, 3, -2.4F, new Item.Properties()));
    public static final DeferredItem<Item> DEBUG_BOW = ITEMS.register("debug_bow", () -> new DebugBowItem(new Item.Properties().durability(3840)));
    public static final DeferredItem<Item> REDSTONE_SHEARS = ITEMS.register("redstone_shears", () -> new ShearsItem(new Item.Properties().durability(250)));
    public static final DeferredItem<Item> COAL_SHEARS = ITEMS.register("coal_shears", () -> new CoalShearsItem(new Item.Properties().durability(32)));
    public static final DeferredItem<Item> COPPER_SHEARS = ITEMS.register("copper_shears", () -> new ShearsItem(new Item.Properties().durability(131)));
    public static final DeferredItem<Item> EXPOSED_COPPER_SHEARS = ITEMS.register("exposed_copper_shears", () -> new ShearsItem(new Item.Properties().durability(131)));
    public static final DeferredItem<Item> WEATHERED_COPPER_SHEARS = ITEMS.register("weathered_copper_shears", () -> new ShearsItem(new Item.Properties().durability(131)));
    public static final DeferredItem<Item> OXIDIZED_COPPER_SHEARS = ITEMS.register("oxidized_copper_shears", () -> new ShearsItem(new Item.Properties().durability(131)));
    public static final DeferredItem<Item> AMETHYST_SHEARS = ITEMS.register("amethyst_shears", () -> new ShearsItem(new Item.Properties().durability(450)));
    public static final DeferredItem<Item> DIAMOND_SHEARS = ITEMS.register("diamond_shears", () -> new ShearsItem(new Item.Properties().durability(1561)));
    public static final DeferredItem<Item> GOLDEN_SHEARS = ITEMS.register("golden_shears", () -> new ShearsItem(new Item.Properties().durability(250)));
    public static final DeferredItem<Item> NETHERITE_SHEARS = ITEMS.register("netherite_shears", () -> new ShearsItem(new Item.Properties().durability(2031).fireResistant()));
    public static final DeferredItem<Item> LAPIS_LAZULI_SHEARS = ITEMS.register("lapis_lazuli_shears", () -> new ShearsItem(new Item.Properties().durability(1671)));
    public static final DeferredItem<Item> EMERALD_SHEARS = ITEMS.register("emerald_shears", () -> new ShearsItem(new Item.Properties().durability(1561)));
    public static final DeferredItem<Item> QUARTZ_SHEARS = ITEMS.register("quartz_shears", () -> new ShearsItem(new Item.Properties().durability(500)));
    public static final DeferredItem<Item> RUBY_SHEARS = ITEMS.register("ruby_shears", () -> new ShearsItem(new Item.Properties().durability(1871)));
    public static final DeferredItem<Item> PLASTEEL_SHEARS = ITEMS.register("plasteel_shears", () -> new CompatShearsItem(new Item.Properties().durability(450), "Rimcraft"));
    public static final DeferredItem<Item> DIAEMERALD_SHEARS = ITEMS.register("diaemerald_shears", () -> new CompatShearsItem(new Item.Properties().durability(725), "My Other Stuff (Others)"));
    public static final DeferredItem<Item> MAGENTIC_CRYSTAL_SHEARS = ITEMS.register("crystal_shears", () -> new CompatShearsItem(new Item.Properties().durability(861), "My Other Stuff (Others)"));
    public static final DeferredItem<Item> MAGENTIC_SHEARS = ITEMS.register("light_magenta_shears", () -> new CompatShearsItem(new Item.Properties().durability(861), "My Other Stuff (Others)"));
    public static final DeferredItem<Item> ALAN_AI_SHEARS = ITEMS.register("alan_ai_shears", () -> new CompatShearsItem(new Item.Properties().durability(600), "My Other Stuff (Others)"));
    public static final DeferredItem<Item> ALICE_AI_SHEARS = ITEMS.register("alice_ai_shears", () -> new CompatShearsItem(new Item.Properties().durability(600), "My Other Stuff (Others)"));
    public static final DeferredItem<Item> INNO_AI_SHEARS = ITEMS.register("inno_ai_shears", () -> new CompatShearsItem(new Item.Properties().durability(600), "My Other Stuff (Others)"));
    public static final DeferredItem<Item> NICOLAS_AI_SHEARS = ITEMS.register("nicolas_ai_shears", () -> new CompatShearsItem(new Item.Properties().durability(600), "My Other Stuff (Others)"));
    public static final DeferredItem<Item> QUARTZ_HELMET = ITEMS.register("quartz_helmet", () -> new ArmorItem(VSArmors.QUARTZ, ArmorItem.Type.HELMET, new Item.Properties()));
    public static final DeferredItem<Item> QUARTZ_CHESTPLATE = ITEMS.register("quartz_chestplate", () -> new ArmorItem(VSArmors.QUARTZ, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final DeferredItem<Item> QUARTZ_LEGGINGS = ITEMS.register("quartz_leggings", () -> new ArmorItem(VSArmors.QUARTZ, ArmorItem.Type.LEGGINGS, new Item.Properties()));
    public static final DeferredItem<Item> QUARTZ_BOOTS = ITEMS.register("quartz_boots", () -> new ArmorItem(VSArmors.QUARTZ, ArmorItem.Type.BOOTS, new Item.Properties()));
    public static final DeferredItem<Item> QUARTZ_HORSE_ARMOR = ITEMS.register("quartz_horse_armor", () -> new HorseArmorItem(9, Variants.resourceLoc("textures/entity/horse/armor/horse_armor_quartz.png"), new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> EMERALD_HELMET = ITEMS.register("emerald_helmet", () -> new ArmorItem(VSArmors.EMERALD, ArmorItem.Type.HELMET, new Item.Properties()));
    public static final DeferredItem<Item> EMERALD_CHESTPLATE = ITEMS.register("emerald_chestplate", () -> new ArmorItem(VSArmors.EMERALD, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final DeferredItem<Item> EMERALD_LEGGINGS = ITEMS.register("emerald_leggings", () -> new ArmorItem(VSArmors.EMERALD, ArmorItem.Type.LEGGINGS, new Item.Properties()));
    public static final DeferredItem<Item> EMERALD_BOOTS = ITEMS.register("emerald_boots", () -> new ArmorItem(VSArmors.EMERALD, ArmorItem.Type.BOOTS, new Item.Properties()));
    public static final DeferredItem<Item> EMPTY_ARMOR_SLOT_HELMET = ITEMS.register("empty_armor_slot_helmet", () -> new ArmorItem(VSArmors.EMPTY_SLOT, ArmorItem.Type.HELMET, new Item.Properties()));
    public static final DeferredItem<Item> EMPTY_ARMOR_SLOT_CHESTPLATE = ITEMS.register("empty_armor_slot_chestplate", () -> new ArmorItem(VSArmors.EMPTY_SLOT, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final DeferredItem<Item> EMPTY_ARMOR_SLOT_LEGGINGS = ITEMS.register("empty_armor_slot_leggings", () -> new ArmorItem(VSArmors.EMPTY_SLOT, ArmorItem.Type.LEGGINGS, new Item.Properties()));
    public static final DeferredItem<Item> EMPTY_ARMOR_SLOT_BOOTS = ITEMS.register("empty_armor_slot_boots", () -> new ArmorItem(VSArmors.EMPTY_SLOT, ArmorItem.Type.BOOTS, new Item.Properties()));
    public static final DeferredItem<Item> EMPTY_ARMOR_SLOT_SHIELD = ITEMS.register("empty_armor_slot_shield", () -> new VSShieldItem(new Item.Properties().durability(496)));
    public static final DeferredItem<Item> COPPER_CHESTPLATE = ITEMS.register("copper_chestplate", () -> new ArmorItem(VSArmors.COPPER, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final DeferredItem<Item> PHANTOM_MEMBRANE_TUNIC = ITEMS.register("phantom_membrane_sweatchest", () -> new ArmorItem(VSArmors.PHANTOM_MEMBRANE, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final DeferredItem<Item> RABBIT_HIDE_TUNIC = ITEMS.register("rabbit_hide_sweatchest", () -> new ArmorItem(VSArmors.RABBIT_HIDE, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final DeferredItem<Item> WOOL_SWEATER = ITEMS.register("wool_sweatchest", () -> new WoolArmorItem(VSArmors.WOOL, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final DeferredItem<Item> IRON_SPYGLASS = ITEMS.register("iron_spyglass", () -> new SpyglassItem(new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> DIAMOND_SPYGLASS = ITEMS.register("diamond_spyglass", () -> new SpyglassItem(new Item.Properties().stacksTo(1)));
    public static final DeferredItem<Item> NETHERITE_SPYGLASS = ITEMS.register("netherite_spyglass", () -> new SpyglassItem(new Item.Properties().stacksTo(1).fireResistant()));
}
