package melonystudios.variants.item;

import com.google.common.collect.Lists;
import melonystudios.variants.Variants;
import melonystudios.variants.block.VSBlocks;
import melonystudios.variants.blockentity.renderer.VSItemStackBlockEntityRenderer;
import melonystudios.variants.effect.VSEffectInstance;
import melonystudios.variants.effect.VSEffects;
import melonystudios.variants.entity.VSEntities;
import melonystudios.variants.fluid.VSFluids;
import melonystudios.variants.item.custom.*;
import melonystudios.variants.item.custom.bottle.*;
import melonystudios.variants.item.custom.dispenser.*;
import melonystudios.variants.item.custom.food.*;
import melonystudios.variants.sound.VSSounds;
import melonystudios.variants.consumable.custom.*;
import melonystudios.variants.util.tab.VSBlockTab;
import melonystudios.variants.util.tab.VSBreweryTab;
import melonystudios.variants.util.tab.VSTab;
import net.minecraft.client.renderer.tileentity.ItemStackTileEntityRenderer;
import net.minecraft.fluid.Fluids;
import net.minecraft.item.*;
import net.minecraft.potion.Effects;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

import java.util.concurrent.Callable;

public class VSItems {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, Variants.MOD_ID);
    public static final DefaultConsumeBehavior DEFAULT_BEHAVIOR = new DefaultConsumeBehavior();

    // Blocks
    public static final RegistryObject<Item> PLAIN_BIRCH_BOOKSHELF = ITEMS.register("plain_birch_bookshelf", () -> new CompatBlockItem(VSBlocks.PLAIN_BIRCH_BOOKSHELF.get(), new Item.Properties().tab(VSBlockTab.TAB), "Fabricio2010's Pack"));
    public static final RegistryObject<Item> AZURE_BLUET_LEAVES = ITEMS.register("azure_bluet_leaves", () -> new BlockItem(VSBlocks.AZURE_BLUET_LEAVES.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_LOG = ITEMS.register("painting_log", () -> new BlockItem(VSBlocks.PAINTING_LOG.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_WOOD = ITEMS.register("painting_wood", () -> new BlockItem(VSBlocks.PAINTING_WOOD.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> STRIPPED_PAINTING_LOG = ITEMS.register("stripped_painting_log", () -> new BlockItem(VSBlocks.STRIPPED_PAINTING_LOG.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> STRIPPED_PAINTING_WOOD = ITEMS.register("stripped_painting_wood", () -> new BlockItem(VSBlocks.STRIPPED_PAINTING_WOOD.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_LEAVES = ITEMS.register("painting_leaves", () -> new BlockItem(VSBlocks.PAINTING_LEAVES.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_PLANKS = ITEMS.register("painting_planks", () -> new BlockItem(VSBlocks.PAINTING_PLANKS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_STAIRS = ITEMS.register("painting_stairs", () -> new BlockItem(VSBlocks.PAINTING_STAIRS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_SLAB = ITEMS.register("painting_slab", () -> new BlockItem(VSBlocks.PAINTING_SLAB.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_FENCE = ITEMS.register("painting_fence", () -> new BlockItem(VSBlocks.PAINTING_FENCE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_FENCE_GATE = ITEMS.register("painting_fence_gate", () -> new BlockItem(VSBlocks.PAINTING_FENCE_GATE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_PRESSURE_PLATE = ITEMS.register("painting_pressure_plate", () -> new BlockItem(VSBlocks.PAINTING_PRESSURE_PLATE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_BUTTON = ITEMS.register("painting_button", () -> new BlockItem(VSBlocks.PAINTING_BUTTON.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_TRAPDOOR = ITEMS.register("painting_trapdoor", () -> new BlockItem(VSBlocks.PAINTING_TRAPDOOR.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_TRAPDOOR_ALBAN = ITEMS.register("alban_trapdoor", () -> new BlockItem(VSBlocks.PAINTING_TRAPDOOR_ALBAN.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_TRAPDOOR_AZTEC = ITEMS.register("aztec_trapdoor", () -> new BlockItem(VSBlocks.PAINTING_TRAPDOOR_AZTEC.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_TRAPDOOR_AZTEC2 = ITEMS.register("aztec2_trapdoor", () -> new BlockItem(VSBlocks.PAINTING_TRAPDOOR_AZTEC2.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_TRAPDOOR_BOMB = ITEMS.register("bomb_trapdoor", () -> new BlockItem(VSBlocks.PAINTING_TRAPDOOR_BOMB.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_TRAPDOOR_KEBAB = ITEMS.register("kebab_trapdoor", () -> new BlockItem(VSBlocks.PAINTING_TRAPDOOR_KEBAB.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_TRAPDOOR_PLANT = ITEMS.register("plant_trapdoor", () -> new BlockItem(VSBlocks.PAINTING_TRAPDOOR_PLANT.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_TRAPDOOR_WASTELAND = ITEMS.register("wasteland_trapdoor", () -> new BlockItem(VSBlocks.PAINTING_TRAPDOOR_WASTELAND.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_DOOR = ITEMS.register("painting_door", () -> new BlockItem(VSBlocks.PAINTING_DOOR.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_DOOR_WANDERER = ITEMS.register("wanderer_door", () -> new BlockItem(VSBlocks.PAINTING_DOOR_WANDERER.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_DOOR_GRAHAM = ITEMS.register("graham_door", () -> new BlockItem(VSBlocks.PAINTING_DOOR_GRAHAM.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_DOOR_FIRST = ITEMS.register("first_door", () -> new CompatBlockItem(VSBlocks.PAINTING_DOOR_FIRST.get(), new Item.Properties().tab(VSBlockTab.TAB), "Fabricio2010's Pack"));
    public static final RegistryObject<Item> PAINTING_SIGN = ITEMS.register("painting_sign", () -> new SignItem(new Item.Properties().stacksTo(16).tab(VSBlockTab.TAB), VSBlocks.PAINTING_SIGN.get(), VSBlocks.PAINTING_WALL_SIGN.get()));
    public static final RegistryObject<Item> ENDERWOOD_STEM = ITEMS.register("enderwood_stem", () -> new BlockItem(VSBlocks.ENDERWOOD_STEM.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDERWOOD_HYPHAE = ITEMS.register("enderwood_hyphae", () -> new BlockItem(VSBlocks.ENDERWOOD_HYPHAE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> STRIPPED_ENDERWOOD_STEM = ITEMS.register("stripped_enderwood_stem", () -> new BlockItem(VSBlocks.STRIPPED_ENDERWOOD_STEM.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> STRIPPED_ENDERWOOD_HYPHAE = ITEMS.register("stripped_enderwood_hyphae", () -> new BlockItem(VSBlocks.STRIPPED_ENDERWOOD_HYPHAE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDER_WART_BLOCK = ITEMS.register("ender_wart_block", () -> new BlockItem(VSBlocks.ENDER_WART_BLOCK.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDER_NYLIUM = ITEMS.register("ender_nylium", () -> new BlockItem(VSBlocks.ENDER_NYLIUM.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDER_FARMLAND = ITEMS.register("ender_farmland", () -> new BlockItem(VSBlocks.ENDER_FARMLAND.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDERWOOD_PLANKS = ITEMS.register("enderwood_planks", () -> new BlockItem(VSBlocks.ENDERWOOD_PLANKS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDERWOOD_BOOKSHELF = ITEMS.register("enderwood_bookshelf", () -> new BlockItem(VSBlocks.ENDERWOOD_BOOKSHELF.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDERWOOD_STAIRS = ITEMS.register("enderwood_stairs", () -> new BlockItem(VSBlocks.ENDERWOOD_STAIRS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDERWOOD_SLAB = ITEMS.register("enderwood_slab", () -> new BlockItem(VSBlocks.ENDERWOOD_SLAB.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDERWOOD_FENCE = ITEMS.register("enderwood_fence", () -> new BlockItem(VSBlocks.ENDERWOOD_FENCE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDERWOOD_FENCE_GATE = ITEMS.register("enderwood_fence_gate", () -> new BlockItem(VSBlocks.ENDERWOOD_FENCE_GATE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDERWOOD_PRESSURE_PLATE = ITEMS.register("enderwood_pressure_plate", () -> new BlockItem(VSBlocks.ENDERWOOD_PRESSURE_PLATE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDERWOOD_BUTTON = ITEMS.register("enderwood_button", () -> new BlockItem(VSBlocks.ENDERWOOD_BUTTON.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDERWOOD_TRAPDOOR = ITEMS.register("enderwood_trapdoor", () -> new BlockItem(VSBlocks.ENDERWOOD_TRAPDOOR.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDERWOOD_DOOR = ITEMS.register("enderwood_door", () -> new BlockItem(VSBlocks.ENDERWOOD_DOOR.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDERWOOD_SIGN = ITEMS.register("enderwood_sign", () -> new SignItem(new Item.Properties().stacksTo(16).tab(VSBlockTab.TAB), VSBlocks.ENDERWOOD_SIGN.get(), VSBlocks.ENDERWOOD_WALL_SIGN.get()));
    public static final RegistryObject<Item> ELDER_SEA_LANTERN = ITEMS.register("elder_sea_lantern", () -> new BlockItem(VSBlocks.ELDER_SEA_LANTERN.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ELDER_PRISMARINE = ITEMS.register("elder_prismarine", () -> new BlockItem(VSBlocks.ELDER_PRISMARINE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ELDER_PRISMARINE_STAIRS = ITEMS.register("elder_prismarine_stairs", () -> new BlockItem(VSBlocks.ELDER_PRISMARINE_STAIRS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ELDER_PRISMARINE_SLAB = ITEMS.register("elder_prismarine_slab", () -> new BlockItem(VSBlocks.ELDER_PRISMARINE_SLAB.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ELDER_PRISMARINE_WALL = ITEMS.register("elder_prismarine_wall", () -> new BlockItem(VSBlocks.ELDER_PRISMARINE_WALL.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ELDER_PRISMARINE_BRICKS = ITEMS.register("elder_prismarine_bricks", () -> new BlockItem(VSBlocks.ELDER_PRISMARINE_BRICKS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ELDER_PRISMARINE_BRICK_STAIRS = ITEMS.register("elder_prismarine_brick_stairs", () -> new BlockItem(VSBlocks.ELDER_PRISMARINE_BRICK_STAIRS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ELDER_PRISMARINE_BRICK_SLAB = ITEMS.register("elder_prismarine_brick_slab", () -> new BlockItem(VSBlocks.ELDER_PRISMARINE_BRICK_SLAB.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> DARK_ELDER_PRISMARINE = ITEMS.register("dark_elder_prismarine", () -> new BlockItem(VSBlocks.DARK_ELDER_PRISMARINE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> DARK_ELDER_PRISMARINE_STAIRS = ITEMS.register("dark_elder_prismarine_stairs", () -> new BlockItem(VSBlocks.DARK_ELDER_PRISMARINE_STAIRS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> DARK_ELDER_PRISMARINE_SLAB = ITEMS.register("dark_elder_prismarine_slab", () -> new BlockItem(VSBlocks.DARK_ELDER_PRISMARINE_SLAB.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> MOSSY_END_STONE_BRICKS = ITEMS.register("mossy_end_stone_bricks", () -> new BlockItem(VSBlocks.MOSSY_END_STONE_BRICKS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> INFESTED_MOSSY_END_STONE_BRICKS = ITEMS.register("infested_mossy_end_stone_bricks", () -> new BlockItem(VSBlocks.INFESTED_MOSSY_END_STONE_BRICKS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> MOSSY_END_STONE_BRICK_STAIRS = ITEMS.register("mossy_end_stone_brick_stairs", () -> new BlockItem(VSBlocks.MOSSY_END_STONE_BRICK_STAIRS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> MOSSY_END_STONE_BRICK_SLAB = ITEMS.register("mossy_end_stone_brick_slab", () -> new BlockItem(VSBlocks.MOSSY_END_STONE_BRICK_SLAB.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> MOSSY_END_STONE_BRICK_WALL = ITEMS.register("mossy_end_stone_brick_wall", () -> new BlockItem(VSBlocks.MOSSY_END_STONE_BRICK_WALL.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> END_STONE_PILLAR = ITEMS.register("end_stone_pillar", () -> new BlockItem(VSBlocks.END_STONE_PILLAR.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> CHISELED_END_STONE_BRICKS = ITEMS.register("chiseled_end_stone_bricks", () -> new BlockItem(VSBlocks.CHISELED_END_STONE_BRICKS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> INFESTED_CHISELED_END_STONE_BRICKS = ITEMS.register("infested_chiseled_end_stone_bricks", () -> new BlockItem(VSBlocks.INFESTED_CHISELED_END_STONE_BRICKS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> MOSSY_PURPUR_BLOCK = ITEMS.register("mossy_purpur_block", () -> new BlockItem(VSBlocks.MOSSY_PURPUR_BLOCK.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> INFESTED_MOSSY_PURPUR_BLOCK = ITEMS.register("infested_mossy_purpur_block", () -> new BlockItem(VSBlocks.INFESTED_MOSSY_PURPUR_BLOCK.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> MOSSY_PURPUR_STAIRS = ITEMS.register("mossy_purpur_stairs", () -> new BlockItem(VSBlocks.MOSSY_PURPUR_STAIRS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> MOSSY_PURPUR_SLAB = ITEMS.register("mossy_purpur_slab", () -> new BlockItem(VSBlocks.MOSSY_PURPUR_SLAB.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> MOSSY_PURPUR_WALL = ITEMS.register("mossy_purpur_wall", () -> new BlockItem(VSBlocks.MOSSY_PURPUR_WALL.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> SMOOTH_PURPUR = ITEMS.register("smooth_purpur", () -> new BlockItem(VSBlocks.SMOOTH_PURPUR.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> SMOOTH_PURPUR_SLAB = ITEMS.register("smooth_purpur_slab", () -> new BlockItem(VSBlocks.SMOOTH_PURPUR_SLAB.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> CHISELED_PURPUR_BLOCK = ITEMS.register("chiseled_purpur_block", () -> new BlockItem(VSBlocks.CHISELED_PURPUR_BLOCK.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> INFESTED_CHISELED_PURPUR_BLOCK = ITEMS.register("infested_chiseled_purpur_block", () -> new BlockItem(VSBlocks.INFESTED_CHISELED_PURPUR_BLOCK.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> MOSSY_NETHER_BRICKS = ITEMS.register("mossy_nether_bricks", () -> new BlockItem(VSBlocks.MOSSY_NETHER_BRICKS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> INFESTED_MOSSY_NETHER_BRICKS = ITEMS.register("infested_mossy_nether_bricks", () -> new BlockItem(VSBlocks.INFESTED_MOSSY_NETHER_BRICKS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> MOSSY_NETHER_BRICK_STAIRS = ITEMS.register("mossy_nether_brick_stairs", () -> new BlockItem(VSBlocks.MOSSY_NETHER_BRICK_STAIRS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> MOSSY_NETHER_BRICK_SLAB = ITEMS.register("mossy_nether_brick_slab", () -> new BlockItem(VSBlocks.MOSSY_NETHER_BRICK_SLAB.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> MOSSY_NETHER_BRICK_WALL = ITEMS.register("mossy_nether_brick_wall", () -> new BlockItem(VSBlocks.MOSSY_NETHER_BRICK_WALL.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> NETHER_BRICK_PILLAR = ITEMS.register("nether_brick_pillar", () -> new BlockItem(VSBlocks.NETHER_BRICK_PILLAR.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> RED_NETHER_BRICK_FENCE = ITEMS.register("red_nether_brick_fence", () -> new BlockItem(VSBlocks.RED_NETHER_BRICK_FENCE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> CRIMSON_FARMLAND = ITEMS.register("crimson_farmland", () -> new BlockItem(VSBlocks.CRIMSON_FARMLAND.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> WARPED_FARMLAND = ITEMS.register("warped_farmland", () -> new BlockItem(VSBlocks.WARPED_FARMLAND.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> WITHER_BONE_BLOCK = ITEMS.register("wither_bone_block", () -> new BlockItem(VSBlocks.WITHER_BONE_BLOCK.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> CRIMSON_STRAW_BALE = ITEMS.register("crimson_straw_bale", () -> new BlockItem(VSBlocks.CRIMSON_STRAW_BALE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> RAW_DEBRIS_BLOCK = ITEMS.register("raw_debris_block", () -> new BlockItem(VSBlocks.RAW_DEBRIS_BLOCK.get(), new Item.Properties().fireResistant().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_ORE = ITEMS.register("quartz_ore", () -> new BlockItem(VSBlocks.QUARTZ_ORE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> DEEPSLATE_QUARTZ_ORE = ITEMS.register("deepslate_quartz_ore", () -> new BlockItem(VSBlocks.DEEPSLATE_QUARTZ_ORE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> END_QUARTZ_ORE = ITEMS.register("end_quartz_ore", () -> new BlockItem(VSBlocks.END_QUARTZ_ORE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDER_NYLIUM_QUARTZ_ORE = ITEMS.register("ender_nylium_quartz_ore", () -> new BlockItem(VSBlocks.ENDER_NYLIUM_QUARTZ_ORE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> NETHER_COAL_ORE = ITEMS.register("nether_coal_ore", () -> new BlockItem(VSBlocks.NETHER_COAL_ORE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> GOLDEN_CAULDRON = ITEMS.register("golden_cauldron", () -> new BlockItem(VSBlocks.GOLDEN_CAULDRON.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> GOLDEN_BEACON = ITEMS.register("golden_beacon", () -> new BlockItem(VSBlocks.GOLDEN_BEACON.get(), new Item.Properties().rarity(Rarity.RARE).tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_CAULDRON = ITEMS.register("quartz_cauldron", () -> new BlockItem(VSBlocks.QUARTZ_CAULDRON.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_BEACON = ITEMS.register("quartz_beacon", () -> new BlockItem(VSBlocks.QUARTZ_BEACON.get(), new Item.Properties().rarity(Rarity.RARE).tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> DIAMOND_BELL = ITEMS.register("diamond_bell", () -> new BlockItem(VSBlocks.DIAMOND_BELL.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> SOUL_BREWING_STAND = ITEMS.register("soul_brewing_stand", () -> new BlockItem(VSBlocks.SOUL_BREWING_STAND.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> NETHERRACK_LEVER = ITEMS.register("netherrack_lever", () -> new BlockItem(VSBlocks.NETHERRACK_LEVER.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> END_STONE_LEVER = ITEMS.register("end_stone_lever", () -> new BlockItem(VSBlocks.END_STONE_LEVER.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> GLOW_BLACK_WOOL = ITEMS.register("glow_black_wool", () -> new BlockItem(VSBlocks.GLOW_BLACK_WOOL.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> GLOW_BLACK_CARPET = ITEMS.register("glow_black_carpet", () -> new BlockItem(VSBlocks.GLOW_BLACK_CARPET.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> GLOW_BLACK_BED = ITEMS.register("glow_black_bed", () -> new BedItem(VSBlocks.GLOW_BLACK_BED.get(), new Item.Properties().stacksTo(1).setISTER(VSItems::variantsISBERProvider).tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> GLOW_BLACK_STAINED_GLASS = ITEMS.register("glow_black_stained_glass", () -> new BlockItem(VSBlocks.GLOW_BLACK_STAINED_GLASS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> GLOW_BLACK_STAINED_GLASS_PANE = ITEMS.register("glow_black_stained_glass_pane", () -> new BlockItem(VSBlocks.GLOW_BLACK_STAINED_GLASS_PANE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_GLASS = ITEMS.register("quartz_glass", () -> new BlockItem(VSBlocks.QUARTZ_GLASS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_GLASS_PANE = ITEMS.register("quartz_glass_pane", () -> new BlockItem(VSBlocks.QUARTZ_GLASS_PANE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_BARS = ITEMS.register("quartz_bars", () -> new BlockItem(VSBlocks.QUARTZ_BARS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_LADDER = ITEMS.register("quartz_ladder", () -> new BlockItem(VSBlocks.QUARTZ_LADDER.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_CHAIN = ITEMS.register("quartz_chain", () -> new BlockItem(VSBlocks.QUARTZ_CHAIN.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> GOLDEN_CHAIN = ITEMS.register("golden_chain", () -> new BlockItem(VSBlocks.GOLDEN_CHAIN.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> DIAMOND_CHAIN = ITEMS.register("diamond_chain", () -> new BlockItem(VSBlocks.DIAMOND_CHAIN.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> EMERALD_CHAIN = ITEMS.register("emerald_chain", () -> new BlockItem(VSBlocks.EMERALD_CHAIN.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> POTTED_SUGAR_CANE = ITEMS.register("potted_sugar_cane", () -> new BlockItem(VSBlocks.POTTED_SUGAR_CANE.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> POTTED_GOLDEN_CARROTS = ITEMS.register("potted_golden_carrots", () -> new BlockItem(VSBlocks.POTTED_GOLDEN_CARROTS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> POTTED_GRASS = ITEMS.register("potted_grass", () -> new BlockItem(VSBlocks.POTTED_GRASS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> POTTED_GLOW_BLACK_TULIP = ITEMS.register("potted_glow_black_tulip", () -> new BlockItem(VSBlocks.POTTED_GLOW_BLACK_TULIP.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> POTTED_SUNNY_FLOWER = ITEMS.register("potted_sunny_flower", () -> new BlockItem(VSBlocks.POTTED_SUNNY_FLOWER.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> POTTED_PAINTING_SAPLING = ITEMS.register("potted_painting_sapling", () -> new BlockItem(VSBlocks.POTTED_PAINTING_SAPLING.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> POTTED_ENDER_ROOTS = ITEMS.register("potted_ender_roots", () -> new BlockItem(VSBlocks.POTTED_ENDER_ROOTS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> POTTED_ENDER_FUNGUS = ITEMS.register("potted_ender_fungus", () -> new BlockItem(VSBlocks.POTTED_ENDER_FUNGUS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> POTTED_NETHER_WART = ITEMS.register("potted_nether_wart", () -> new BlockItem(VSBlocks.POTTED_NETHER_WART.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> POTTED_WARPED_WART = ITEMS.register("potted_warped_wart", () -> new BlockItem(VSBlocks.POTTED_WARPED_WART.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> POTTED_ENDER_WART = ITEMS.register("potted_ender_wart", () -> new BlockItem(VSBlocks.POTTED_ENDER_WART.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> POTTED_TORCH = ITEMS.register("potted_torch", () -> new BlockItem(VSBlocks.POTTED_TORCH.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> POTTED_SOUL_TORCH = ITEMS.register("potted_soul_torch", () -> new BlockItem(VSBlocks.POTTED_SOUL_TORCH.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> POTTED_REDSTONE_TORCH = ITEMS.register("potted_redstone_torch", () -> new BlockItem(VSBlocks.POTTED_REDSTONE_TORCH.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> GOLDEN_CARROTS = ITEMS.register("golden_carrots", () -> new BlockItem(VSBlocks.GOLDEN_CARROTS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> WILD_CRIMSON_WHEAT = ITEMS.register("wild_crimson_wheat", () -> new BlockItem(VSBlocks.WILD_CRIMSON_WHEAT.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> WILD_SOUL_CARROTS = ITEMS.register("wild_soul_carrots", () -> new BlockItem(VSBlocks.WILD_SOUL_CARROTS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> WILD_WARPED_POTATOES = ITEMS.register("wild_warped_potatoes", () -> new BlockItem(VSBlocks.WILD_WARPED_POTATOES.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> WILD_MELTING_BEETS = ITEMS.register("wild_melting_beets", () -> new BlockItem(VSBlocks.WILD_MELTING_BEETS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> GLOW_BLACK_TULIP = ITEMS.register("glow_black_tulip", () -> new BlockItem(VSBlocks.GLOW_BLACK_TULIP.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> SUNNY_FLOWER = ITEMS.register("sunny_flower", () -> new BlockItem(VSBlocks.SUNNY_FLOWER.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> GLOW_BERRY_BUSH = ITEMS.register("glow_berry_bush", () -> new BlockItem(VSBlocks.GLOW_BERRY_BUSH.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> PAINTING_SAPLING = ITEMS.register("painting_sapling", () -> new BlockItem(VSBlocks.PAINTING_SAPLING.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDER_ROOTS = ITEMS.register("ender_roots", () -> new BlockItem(VSBlocks.ENDER_ROOTS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> END_SPROUTS = ITEMS.register("end_sprouts", () -> new BlockItem(VSBlocks.END_SPROUTS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDER_FUNGUS = ITEMS.register("ender_fungus", () -> new BlockItem(VSBlocks.ENDER_FUNGUS.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> WARPING_VINES = ITEMS.register("warping_vines", () -> new BlockItem(VSBlocks.WARPING_VINES.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> WARPED_WART = ITEMS.register("warped_wart", () -> new BlockNamedItem(VSBlocks.WARPED_WART.get(), new Item.Properties().tab(VSBlockTab.TAB)));
    public static final RegistryObject<Item> ENDER_WART = ITEMS.register("ender_wart", () -> new BlockNamedItem(VSBlocks.ENDER_WART.get(), new Item.Properties().tab(VSBlockTab.TAB)));

    // Items
    public static final RegistryObject<Item> WHITE_SHULKER_SHELL = ITEMS.register("white_shulker_shell", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> INNO_SHULKER_SHELL = ITEMS.register("inno_shulker_shell", () -> new CompatItem(new Item.Properties().tab(VSTab.TAB), "F10 Elements"));
    public static final RegistryObject<Item> ORANGE_SHULKER_SHELL = ITEMS.register("orange_shulker_shell", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> MAGENTA_SHULKER_SHELL = ITEMS.register("magenta_shulker_shell", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> LIGHT_BLUE_SHULKER_SHELL = ITEMS.register("light_blue_shulker_shell", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> GLOW_BLACK_SHULKER_SHELL = ITEMS.register("glow_black_shulker_shell", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> YELLOW_SHULKER_SHELL = ITEMS.register("yellow_shulker_shell", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> LIME_SHULKER_SHELL = ITEMS.register("lime_shulker_shell", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> PINK_SHULKER_SHELL = ITEMS.register("pink_shulker_shell", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> GRAY_SHULKER_SHELL = ITEMS.register("gray_shulker_shell", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> LIGHT_GRAY_SHULKER_SHELL = ITEMS.register("light_gray_shulker_shell", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> CYAN_SHULKER_SHELL = ITEMS.register("cyan_shulker_shell", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> PURPLE_SHULKER_SHELL = ITEMS.register("purple_shulker_shell", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> BLUE_SHULKER_SHELL = ITEMS.register("blue_shulker_shell", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> BROWN_SHULKER_SHELL = ITEMS.register("brown_shulker_shell", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> GREEN_SHULKER_SHELL = ITEMS.register("green_shulker_shell", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> RED_SHULKER_SHELL = ITEMS.register("red_shulker_shell", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> BLACK_SHULKER_SHELL = ITEMS.register("black_shulker_shell", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> SHULKER_SPECTRUM_ICON = ITEMS.register("shulker_spectrum_icon", () -> new Item(new Item.Properties().rarity(Rarity.EPIC).fireResistant()));
    public static final RegistryObject<Item> MUSIC_DISC_DOG = ITEMS.register("music_disc_dog", () -> new MusicDiscItem(2, VSSounds.MUSIC_DISC_DOG, new Item.Properties().rarity(Rarity.UNCOMMON).stacksTo(1).tab(VSTab.TAB)));
    public static final RegistryObject<Item> SPAWNER_MINECART = ITEMS.register("spawner_minecart", () -> new SpawnerMinecartItem(new Item.Properties().stacksTo(1).tab(VSTab.TAB)));
    public static final RegistryObject<Item> MUSHROOM_STEW_BUCKET = ITEMS.register("mushroom_stew_bucket", () -> new PlaceableBucketFoodItem(VSFluids.MUSHROOM_STEW, new Item.Properties().stacksTo(1).craftRemainder(Items.BUCKET).food(Foods.MUSHROOM_STEW).tab(VSTab.TAB)));
    public static final RegistryObject<Item> BEETROOT_SOUP_BUCKET = ITEMS.register("beetroot_soup_bucket", () -> new BucketFoodItem(new Item.Properties().stacksTo(1).food(Foods.BEETROOT_SOUP).tab(VSTab.TAB)));
    public static final RegistryObject<Item> RABBIT_STEW_BUCKET = ITEMS.register("rabbit_stew_bucket", () -> new BucketFoodItem(new Item.Properties().stacksTo(1).food(Foods.RABBIT_STEW).tab(VSTab.TAB)));
    public static final RegistryObject<Item> SUSPICIOUS_STEW_BUCKET = ITEMS.register("suspicious_stew_bucket", () -> new BucketFoodItem(new Item.Properties().stacksTo(1).food(Foods.SUSPICIOUS_STEW).tab(VSTab.TAB)));
    public static final RegistryObject<Item> MELTING_BEET_SOUP_BUCKET = ITEMS.register("melting_beet_soup_bucket", () -> new BucketFoodItem(new Item.Properties().stacksTo(1).food(Foods.BEETROOT_SOUP).tab(VSTab.TAB)));
    public static final RegistryObject<Item> FUNGI_STEW_BUCKET = ITEMS.register("fungi_stew_bucket", () -> new BucketFoodItem(new Item.Properties().stacksTo(1).food(Foods.MUSHROOM_STEW).tab(VSTab.TAB)));
    public static final RegistryObject<Item> END_FUNGI_STEW_BUCKET = ITEMS.register("end_fungi_stew_bucket", () -> new BucketFoodItem(new Item.Properties().stacksTo(1).food(Foods.MUSHROOM_STEW).tab(VSTab.TAB)));
    public static final RegistryObject<Item> SOUL_LAVA_BUCKET = ITEMS.register("soul_lava_bucket", () -> new SoulLavaBucketItem(new Item.Properties().stacksTo(1).craftRemainder(Items.BUCKET).tab(VSTab.TAB)));
    public static final RegistryObject<Item> FISH_BUCKET = ITEMS.register("fish_bucket", () -> new VSFishBucketItem(VSEntities.FISH, () -> Fluids.WATER, new Item.Properties().stacksTo(1).craftRemainder(Items.BUCKET).tab(VSTab.TAB)));
    public static final RegistryObject<Item> FISH_SPAWN_EGG = ITEMS.register("fish_spawn_egg", () -> new ForgeSpawnEggItem(VSEntities.FISH, 0x6B9F93, 0xADBEDB, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> MELTING_BEET_SOUP = ITEMS.register("melting_beet_soup", () -> new SimpleStewItem(DEFAULT_BEHAVIOR, new Item.Properties().stacksTo(1).tab(VSTab.TAB).food(Foods.BEETROOT_SOUP)));
    public static final RegistryObject<Item> FUNGI_STEW = ITEMS.register("fungi_stew", () -> new SimpleStewItem(DEFAULT_BEHAVIOR, new Item.Properties().stacksTo(1).tab(VSTab.TAB).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> END_FUNGI_STEW = ITEMS.register("end_fungi_stew", () -> new SimpleStewItem(DEFAULT_BEHAVIOR, new Item.Properties().stacksTo(1).tab(VSTab.TAB).food(Foods.MUSHROOM_STEW)));
    public static final RegistryObject<Item> PAINTING_BOAT = ITEMS.register("painting_boat", () -> new VSBoatItem(new Item.Properties().stacksTo(1).tab(VSTab.TAB), "painting"));
    public static final RegistryObject<Item> CRIMSON_BOAT = ITEMS.register("crimson_boat", () -> new VSBoatItem(new Item.Properties().stacksTo(1).tab(VSTab.TAB), "crimson"));
    public static final RegistryObject<Item> WARPED_BOAT = ITEMS.register("warped_boat", () -> new VSBoatItem(new Item.Properties().stacksTo(1).tab(VSTab.TAB), "warped"));
    public static final RegistryObject<Item> ENDERWOOD_BOAT = ITEMS.register("enderwood_boat", () -> new VSBoatItem(new Item.Properties().stacksTo(1).tab(VSTab.TAB), "enderwood"));
    public static final RegistryObject<Item> WHITE_STAINED_GLASS_BOTTLE = ITEMS.register("white_stained_glass_bottle", () -> new StainedEmptyGlassBottleItem(DyeColor.WHITE, new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> LIGHT_GRAY_STAINED_GLASS_BOTTLE = ITEMS.register("light_gray_stained_glass_bottle", () -> new StainedEmptyGlassBottleItem(DyeColor.LIGHT_GRAY, new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> GRAY_STAINED_GLASS_BOTTLE = ITEMS.register("gray_stained_glass_bottle", () -> new StainedEmptyGlassBottleItem(DyeColor.GRAY, new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> BLACK_STAINED_GLASS_BOTTLE = ITEMS.register("black_stained_glass_bottle", () -> new StainedEmptyGlassBottleItem(DyeColor.BLACK, new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> BROWN_STAINED_GLASS_BOTTLE = ITEMS.register("brown_stained_glass_bottle", () -> new StainedEmptyGlassBottleItem(DyeColor.BROWN, new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> RED_STAINED_GLASS_BOTTLE = ITEMS.register("red_stained_glass_bottle", () -> new StainedEmptyGlassBottleItem(DyeColor.RED, new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> ORANGE_STAINED_GLASS_BOTTLE = ITEMS.register("orange_stained_glass_bottle", () -> new StainedEmptyGlassBottleItem(DyeColor.ORANGE, new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> YELLOW_STAINED_GLASS_BOTTLE = ITEMS.register("yellow_stained_glass_bottle", () -> new StainedEmptyGlassBottleItem(DyeColor.YELLOW, new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> LIME_STAINED_GLASS_BOTTLE = ITEMS.register("lime_stained_glass_bottle", () -> new StainedEmptyGlassBottleItem(DyeColor.LIME, new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> GREEN_STAINED_GLASS_BOTTLE = ITEMS.register("green_stained_glass_bottle", () -> new StainedEmptyGlassBottleItem(DyeColor.GREEN, new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> CYAN_STAINED_GLASS_BOTTLE = ITEMS.register("cyan_stained_glass_bottle", () -> new StainedEmptyGlassBottleItem(DyeColor.CYAN, new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> LIGHT_BLUE_STAINED_GLASS_BOTTLE = ITEMS.register("light_blue_stained_glass_bottle", () -> new StainedEmptyGlassBottleItem(DyeColor.LIGHT_BLUE, new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> GLOW_BLACK_STAINED_GLASS_BOTTLE = ITEMS.register("glow_black_stained_glass_bottle", () -> new StainedEmptyGlassBottleItem(0x4BDEBA, "variants:glow_black", new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> BLUE_STAINED_GLASS_BOTTLE = ITEMS.register("blue_stained_glass_bottle", () -> new StainedEmptyGlassBottleItem(DyeColor.BLUE, new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> PURPLE_STAINED_GLASS_BOTTLE = ITEMS.register("purple_stained_glass_bottle", () -> new StainedEmptyGlassBottleItem(DyeColor.PURPLE, new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> MAGENTA_STAINED_GLASS_BOTTLE = ITEMS.register("magenta_stained_glass_bottle", () -> new StainedEmptyGlassBottleItem(DyeColor.MAGENTA, new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> PINK_STAINED_GLASS_BOTTLE = ITEMS.register("pink_stained_glass_bottle", () -> new StainedEmptyGlassBottleItem(DyeColor.PINK, new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_GLASS_BOTTLE = ITEMS.register("quartz_glass_bottle", () -> new StainedEmptyGlassBottleItem(0xDDD4C6, "variants:quartz", new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> STAINED_EXPERIENCE_BOTTLE = ITEMS.register("stained_experience_bottle", () -> new StainedExperienceBottleItem(new Item.Properties().rarity(Rarity.UNCOMMON).tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> STAINED_HONEY_BOTTLE = ITEMS.register("stained_honey_bottle", () -> new StainedHoneyBottleItem(new Item.Properties().food(Foods.HONEY_BOTTLE).tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> STAINED_DRAGON_BREATH = ITEMS.register("stained_dragon_breath", () -> new StainedUndrinkableBottleItem(new Item.Properties().rarity(Rarity.UNCOMMON).tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> STAINED_LAVA_BOTTLE = ITEMS.register("stained_lava_bottle", () -> new StainedLavaBottleItem(5, new Item.Properties().stacksTo(8).tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> STAINED_SOUL_LAVA_BOTTLE = ITEMS.register("stained_soul_lava_bottle", () -> new StainedLavaBottleItem(10, new Item.Properties().stacksTo(8).tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> STAINED_MILK_BOTTLE = ITEMS.register("stained_milk_bottle", () -> new StainedMilkBottleItem(new Item.Properties().stacksTo(8).tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> STAINED_POWDER_SNOW_BOTTLE = ITEMS.register("stained_powder_snow_bottle", () -> new StainedDefaultBottleItem(new Item.Properties().stacksTo(8).tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> STAINED_SOPHIE_POTION = ITEMS.register("stained_sophie_potion", () -> new StainedDefaultBottleItem(new Item.Properties().tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> STAINED_POTION = ITEMS.register("stained_potion", () -> new StainedPotionItem(new Item.Properties().stacksTo(1).tab(VSBreweryTab.TAB)));
    public static final RegistryObject<Item> SPLASH_GLASS_BOTTLE = ITEMS.register("splash_glass_bottle", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> LINGERING_GLASS_BOTTLE = ITEMS.register("lingering_glass_bottle", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> SPLASH_EXPERIENCE_BOTTLE = ITEMS.register("splash_experience_bottle", () -> new VSExperienceBottleItem(new Item.Properties().rarity(Rarity.UNCOMMON).tab(VSTab.TAB)));
    public static final RegistryObject<Item> LINGERING_EXPERIENCE_BOTTLE = ITEMS.register("lingering_experience_bottle", () -> new VSExperienceBottleItem(new Item.Properties().rarity(Rarity.UNCOMMON).tab(VSTab.TAB)));
    public static final RegistryObject<Item> SPLASH_DRAGON_BREATH = ITEMS.register("splash_dragon_breath", () -> new DragonBreathBottleItem(new Item.Properties().craftRemainder(VSItems.SPLASH_GLASS_BOTTLE.get()).rarity(Rarity.UNCOMMON).tab(VSTab.TAB)));
    public static final RegistryObject<Item> LINGERING_DRAGON_BREATH = ITEMS.register("lingering_dragon_breath", () -> new DragonBreathBottleItem(new Item.Properties().craftRemainder(VSItems.LINGERING_GLASS_BOTTLE.get()).rarity(Rarity.UNCOMMON).tab(VSTab.TAB)));
    public static final RegistryObject<Item> SPLASH_HONEY_BOTTLE = ITEMS.register("splash_honey_bottle", () -> new BehaviorBottleItem(new MultiBehavior(Lists.newArrayList(new EatItemBehavior(new ItemStack(Items.HONEY_BOTTLE)), new RemoveEffectsBehavior(Lists.newArrayList(Effects.POISON)))), 0xFFD400, new Item.Properties().craftRemainder(VSItems.SPLASH_GLASS_BOTTLE.get()).tab(VSTab.TAB)));
    public static final RegistryObject<Item> LINGERING_HONEY_BOTTLE = ITEMS.register("lingering_honey_bottle", () -> new BehaviorBottleItem(new MultiBehavior(Lists.newArrayList(new EatItemBehavior(new ItemStack(Items.HONEY_BOTTLE)), new RemoveEffectsBehavior(Lists.newArrayList(Effects.POISON)))), 0xFFD400, new Item.Properties().craftRemainder(VSItems.LINGERING_GLASS_BOTTLE.get()).tab(VSTab.TAB)));
    public static final RegistryObject<Item> LAVA_BOTTLE = ITEMS.register("lava_bottle", () -> new LavaBottleItem(5, new Item.Properties().stacksTo(8).craftRemainder(Items.GLASS_BOTTLE).tab(VSTab.TAB)));
    public static final RegistryObject<Item> SPLASH_LAVA_BOTTLE = ITEMS.register("splash_lava_bottle", () -> new BehaviorBottleItem(new IgniteBehavior(100), 0xE38C3F, new Item.Properties().stacksTo(8).craftRemainder(VSItems.SPLASH_GLASS_BOTTLE.get()).tab(VSTab.TAB)));
    public static final RegistryObject<Item> LINGERING_LAVA_BOTTLE = ITEMS.register("lingering_lava_bottle", () -> new BehaviorBottleItem(new IgniteBehavior(100), 0xE38C3F, new Item.Properties().stacksTo(8).craftRemainder(VSItems.LINGERING_GLASS_BOTTLE.get()).tab(VSTab.TAB)));
    public static final RegistryObject<Item> SOUL_LAVA_BOTTLE = ITEMS.register("soul_lava_bottle", () -> new LavaBottleItem(10, new Item.Properties().stacksTo(8).craftRemainder(Items.GLASS_BOTTLE).tab(VSTab.TAB)));
    public static final RegistryObject<Item> SPLASH_SOUL_LAVA_BOTTLE = ITEMS.register("splash_soul_lava_bottle", () -> new BehaviorBottleItem(new IgniteBehavior(200), 0x28CBC9, new Item.Properties().stacksTo(8).craftRemainder(VSItems.SPLASH_GLASS_BOTTLE.get()).tab(VSTab.TAB)));
    public static final RegistryObject<Item> LINGERING_SOUL_LAVA_BOTTLE = ITEMS.register("lingering_soul_lava_bottle", () -> new BehaviorBottleItem(new IgniteBehavior(200), 0x28CBC9, new Item.Properties().stacksTo(8).craftRemainder(VSItems.LINGERING_GLASS_BOTTLE.get()).tab(VSTab.TAB)));
    public static final RegistryObject<Item> MILK_BOTTLE = ITEMS.register("milk_bottle", () -> new MilkBottleItem(new Item.Properties().stacksTo(8).craftRemainder(Items.GLASS_BOTTLE).tab(VSTab.TAB)));
    public static final RegistryObject<Item> SPLASH_MILK_BOTTLE = ITEMS.register("splash_milk_bottle", () -> new BehaviorBottleItem(new ClearMobEffectsBehavior(), 0xDDF3F5, new Item.Properties().stacksTo(8).craftRemainder(VSItems.SPLASH_GLASS_BOTTLE.get()).tab(VSTab.TAB)));
    public static final RegistryObject<Item> LINGERING_MILK_BOTTLE = ITEMS.register("lingering_milk_bottle", () -> new BehaviorBottleItem(new ClearMobEffectsBehavior(), 0xDDF3F5, new Item.Properties().stacksTo(8).craftRemainder(VSItems.LINGERING_GLASS_BOTTLE.get()).tab(VSTab.TAB)));
    public static final RegistryObject<Item> POWDER_SNOW_BOTTLE = ITEMS.register("powder_snow_bottle", () -> new PowderSnowBottleItem(new Item.Properties().stacksTo(8).craftRemainder(Items.GLASS_BOTTLE).tab(VSTab.TAB)));
    public static final RegistryObject<Item> SPLASH_POWDER_SNOW_BOTTLE = ITEMS.register("splash_powder_snow_bottle", () -> new BehaviorBottleItem(DEFAULT_BEHAVIOR, 0xEBFDFD, new Item.Properties().stacksTo(8).craftRemainder(VSItems.SPLASH_GLASS_BOTTLE.get()).tab(VSTab.TAB)));
    public static final RegistryObject<Item> LINGERING_POWDER_SNOW_BOTTLE = ITEMS.register("lingering_powder_snow_bottle", () -> new BehaviorBottleItem(DEFAULT_BEHAVIOR, 0xEBFDFD, new Item.Properties().stacksTo(8).craftRemainder(VSItems.LINGERING_GLASS_BOTTLE.get()).tab(VSTab.TAB)));
    public static final RegistryObject<Item> SPLASH_SOPHIE_POTION = ITEMS.register("splash_soph_potion", () -> new SophiePotionItem(new Item.Properties().food(VSFoods.SOPHIE_POTION).tab(VSTab.TAB), "Edits"));
    public static final RegistryObject<Item> LINGERING_SOPHIE_POTION = ITEMS.register("lingering_sophie_potion", () -> new SophiePotionItem(new Item.Properties().food(VSFoods.SOPHIE_POTION).tab(VSTab.TAB), "Edits"));
    public static final RegistryObject<Item> STYLISED_POT = ITEMS.register("stylised_pot", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> REDSTONE_POT = ITEMS.register("redstone_pot", () -> new StylisedPotItem(new Item.Properties().stacksTo(16).tab(VSTab.TAB), Lists.newArrayList(new VSEffectInstance(VSEffects.REDSTONE_POISONING, 200))));
    public static final RegistryObject<Item> BLUESTONE_POT = ITEMS.register("bluestone_pot", () -> new StylisedPotItem(new Item.Properties().stacksTo(16).tab(VSTab.TAB), "Fabricio2010's Pack", Lists.newArrayList(new VSEffectInstance(VSEffects.BLUESTONE_POISONING, 200))));
    public static final RegistryObject<Item> GLOWSTONE_POT = ITEMS.register("glowstone_pot", () -> new StylisedPotItem(new Item.Properties().stacksTo(16).tab(VSTab.TAB), Lists.newArrayList(new VSEffectInstance(VSEffects.GLOWSTONE_POISONING, 200), new VSEffectInstance(() -> Effects.GLOWING, 200))));
    public static final RegistryObject<Item> GUNPOWDER_POT = ITEMS.register("gunpowder_pot", () -> new StylisedPotItem(new Item.Properties().stacksTo(16).tab(VSTab.TAB), Lists.newArrayList(new VSEffectInstance(VSEffects.GUNPOWDER_POISONING, 200))));
    public static final RegistryObject<Item> EXPLOSIVE_BLEND_POT = ITEMS.register("explosive_blend_pot", () -> new StylisedPotItem(new Item.Properties().stacksTo(16).tab(VSTab.TAB), "Creeper Edits", Lists.newArrayList(new VSEffectInstance(VSEffects.EXPLOSIVE_BLEND_POISONING, 200))));
    public static final RegistryObject<Item> SUGAR_POT = ITEMS.register("sugar_pot", () -> new StylisedPotItem(new Item.Properties().stacksTo(16).tab(VSTab.TAB), Lists.newArrayList(new VSEffectInstance(() -> Effects.MOVEMENT_SPEED, 100))));
    public static final RegistryObject<Item> SWEET_BERRY_POT = ITEMS.register("sweet_berry_pot", () -> new StylisedPotItem(DEFAULT_BEHAVIOR, new Item.Properties().stacksTo(16).food(VSFoods.BERRY_POTS).tab(VSTab.TAB)));
    public static final RegistryObject<Item> GLOW_BERRY_POT = ITEMS.register("glow_berry_pot", () -> new StylisedPotItem(DEFAULT_BEHAVIOR, new Item.Properties().stacksTo(16).food(VSFoods.BERRY_POTS).tab(VSTab.TAB)));
    public static final RegistryObject<Item> HONEY_BALL = ITEMS.register("honey_ball", () -> new HoneyBallItem(new RemoveEffectsBehavior(Lists.newArrayList(Effects.POISON)), new Item.Properties().food(Foods.HONEY_BOTTLE).tab(VSTab.TAB)));
    public static final RegistryObject<Item> RAW_FISH = ITEMS.register("fish", () -> new ConsumableItem(true, DEFAULT_BEHAVIOR, new Item.Properties().food(Foods.COD).tab(VSTab.TAB)));
    public static final RegistryObject<Item> COOKED_FISH = ITEMS.register("cooked_fish", () -> new ConsumableItem(true, DEFAULT_BEHAVIOR, new Item.Properties().food(Foods.COOKED_COD).tab(VSTab.TAB)));
    public static final RegistryObject<Item> CRIMSON_WHEAT_SEEDS = ITEMS.register("crimson_wheat_seeds", () -> new BlockNamedItem(VSBlocks.CRIMSON_WHEAT.get(), new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> CRIMSON_WHEAT = ITEMS.register("crimson_wheat", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> CRIMSON_LOAF = ITEMS.register("crimson_loaf", () -> new SavedConsumableItem(new ApplyMobEffectsBehavior(Lists.newArrayList(new VSEffectInstance(() -> Effects.FIRE_RESISTANCE, 300))), new Item.Properties().food(Foods.BREAD).tab(VSTab.TAB)));
    public static final RegistryObject<Item> SOUL_CARROT = ITEMS.register("soul_carrot", () -> new BlockNamedItem(VSBlocks.SOUL_CARROTS.get(), new Item.Properties().food(Foods.CARROT).tab(VSTab.TAB))); // too lazy to make it compatible with consume behaviors (~isa)
    public static final RegistryObject<Item> QUARTZ_CARROT = ITEMS.register("quartz_carrot", () -> new ConsumableItem(false, DEFAULT_BEHAVIOR, new Item.Properties().food(Foods.GOLDEN_CARROT).tab(VSTab.TAB)));
    public static final RegistryObject<Item> WARPED_POTATO = ITEMS.register("warped_potato", () -> new BlockNamedItem(VSBlocks.WARPED_POTATOES.get(), new Item.Properties().food(Foods.POTATO).tab(VSTab.TAB)));
    public static final RegistryObject<Item> BAKED_WARPED_POTATO = ITEMS.register("baked_warped_potato", () -> new ConsumableItem(false, DEFAULT_BEHAVIOR, new Item.Properties().food(Foods.BAKED_POTATO).tab(VSTab.TAB)));
    public static final RegistryObject<Item> WITHERED_WARPED_POTATO = ITEMS.register("withered_warped_potato", () -> new SavedConsumableItem(new ApplyMobEffectsBehavior(Lists.newArrayList(new VSEffectInstance(() -> Effects.WITHER, 100).withChance(0.6F))), new Item.Properties().food(VSFoods.WITHERED_WARPED_POTATO).tab(VSTab.TAB)));
    public static final RegistryObject<Item> MELTING_BEET_SEEDS = ITEMS.register("melting_beet_seeds", () -> new BlockNamedItem(VSBlocks.MELTING_BEETS.get(), new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> MELTING_BEET = ITEMS.register("melting_beet", () -> new ConsumableItem(false, DEFAULT_BEHAVIOR, new Item.Properties().food(Foods.BEETROOT).tab(VSTab.TAB)));
    public static final RegistryObject<Item> OAK_STICK = ITEMS.register("oak_stick", () -> new FlammableItem(100, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> SPRUCE_STICK = ITEMS.register("spruce_stick", () -> new FlammableItem(100, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> BIRCH_STICK = ITEMS.register("birch_stick", () -> new FlammableItem(100, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> JUNGLE_STICK = ITEMS.register("jungle_stick", () -> new FlammableItem(100, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> ACACIA_STICK = ITEMS.register("acacia_stick", () -> new FlammableItem(100, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> DARK_OAK_STICK = ITEMS.register("dark_oak_stick", () -> new FlammableItem(100, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> PAINTING_STICK = ITEMS.register("painting_stick", () -> new FlammableItem(100, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> CRIMSON_STICK = ITEMS.register("crimson_stick", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> WARPED_STICK = ITEMS.register("warped_stick", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> ENDERWOOD_STICK = ITEMS.register("enderwood_stick", () -> new FlammableItem(100, new Item.Properties().stacksTo(1).tab(VSTab.TAB)));
    public static final RegistryObject<Item> OAK_DEBUG_STICK = ITEMS.register("oak_debug_stick", () -> new VSDebugStickItem(100, new Item.Properties().stacksTo(1).rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> SPRUCE_DEBUG_STICK = ITEMS.register("spruce_debug_stick", () -> new VSDebugStickItem(100, new Item.Properties().stacksTo(1).rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> BIRCH_DEBUG_STICK = ITEMS.register("birch_debug_stick", () -> new VSDebugStickItem(100, new Item.Properties().stacksTo(1).rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> JUNGLE_DEBUG_STICK = ITEMS.register("jungle_debug_stick", () -> new VSDebugStickItem(100, new Item.Properties().stacksTo(1).rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> ACACIA_DEBUG_STICK = ITEMS.register("acacia_debug_stick", () -> new VSDebugStickItem(100, new Item.Properties().stacksTo(1).rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> DARK_OAK_DEBUG_STICK = ITEMS.register("dark_oak_debug_stick", () -> new VSDebugStickItem(100, new Item.Properties().stacksTo(1).rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> PAINTING_DEBUG_STICK = ITEMS.register("painting_debug_stick", () -> new VSDebugStickItem(100, new Item.Properties().stacksTo(1).rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> CRIMSON_DEBUG_STICK = ITEMS.register("crimson_debug_stick", () -> new VSDebugStickItem(new Item.Properties().stacksTo(1).rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> WARPED_DEBUG_STICK = ITEMS.register("warped_debug_stick", () -> new VSDebugStickItem(new Item.Properties().stacksTo(1).rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> ENDERWOOD_DEBUG_STICK = ITEMS.register("enderwood_debug_stick", () -> new VSDebugStickItem(100, new Item.Properties().stacksTo(1).rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> NETHERITE_ROD = ITEMS.register("netherite_rod", () -> new Item(new Item.Properties().tab(VSTab.TAB).fireResistant()));
    public static final RegistryObject<Item> OAK_BOWL = ITEMS.register("oak_bowl", () -> new FlammableItem(100, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> SPRUCE_BOWL = ITEMS.register("spruce_bowl", () -> new FlammableItem(100, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> BIRCH_BOWL = ITEMS.register("birch_bowl", () -> new FlammableItem(100, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> JUNGLE_BOWL = ITEMS.register("jungle_bowl", () -> new FlammableItem(100, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> ACACIA_BOWL = ITEMS.register("acacia_bowl", () -> new FlammableItem(100, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> DARK_OAK_BOWL = ITEMS.register("dark_oak_bowl", () -> new FlammableItem(100, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> PAINTING_BOWL = ITEMS.register("painting_bowl", () -> new FlammableItem(100, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> CRIMSON_BOWL = ITEMS.register("crimson_bowl", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> WARPED_BOWL = ITEMS.register("warped_bowl", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> ENDERWOOD_BOWL = ITEMS.register("enderwood_bowl", () -> new FlammableItem(100, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> CRYSTALLIZED_HONEY = ITEMS.register("crystallized_honey", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> SOUL_BLAZE_ROD = ITEMS.register("soul_blaze_rod", () -> new FlammableItem(4800, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> SOUL_BLAZE_POWDER = ITEMS.register("soul_blaze_powder", () -> new FlammableItem(2400, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> SOUL_CHARGE = ITEMS.register("soul_charge", () -> new SoulChargeItem(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> RED_NETHER_BRICK = ITEMS.register("red_nether_brick", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> EXPOSED_COPPER_INGOT = ITEMS.register("exposed_copper_ingot", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> WEATHERED_COPPER_INGOT = ITEMS.register("weathered_copper_ingot", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> OXIDIZED_COPPER_INGOT = ITEMS.register("oxidized_copper_ingot", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> RAW_DEBRIS = ITEMS.register("raw_debris", () -> new Item(new Item.Properties().fireResistant().tab(VSTab.TAB)));
    public static final RegistryObject<Item> DIAMOND_SHARD = ITEMS.register("diamond_shard", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> EMERALD_SHARD = ITEMS.register("emerald_shard", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> QUARTZ_SHARD = ITEMS.register("quartz_shard", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> PURPLE_IRON_NUGGET = ITEMS.register("purple_iron_nugget", () -> new CompatItem(new Item.Properties().tab(VSTab.TAB), "Edits"));
    public static final RegistryObject<Item> GLOW_BLACK_DYE = ITEMS.register("glow_black_dye", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> IRON_TIE = ITEMS.register("iron_tie", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> POWERED_TIE = ITEMS.register("powered_tie", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> CORNER_IRON_TIE = ITEMS.register("corner_iron_tie", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> WOODEN_RAILBED = ITEMS.register("wooden_railbed", () -> new FlammableItem(350, new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> POWERED_RAILBED = ITEMS.register("powered_railbed", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> DETECTOR_PLATE = ITEMS.register("detector_plate", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> ELDER_PRISMARINE_SHARD = ITEMS.register("elder_prismarine_shard", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> ELDER_PRISMARINE_CRYSTALS = ITEMS.register("elder_prismarine_crystals", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> WITHER_BONE = ITEMS.register("wither_bone", () -> new Item(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> WITHER_BONE_MEAL = ITEMS.register("wither_bone_meal", () -> new WitherBoneMealItem(new Item.Properties().tab(VSTab.TAB)));
    public static final RegistryObject<Item> EXPONENTIAL_MUSHROOM_STEW = ITEMS.register("exponential_mushroom_stew", () -> new ExponentialStewItem(DEFAULT_BEHAVIOR, new Item.Properties().stacksTo(1).food(Foods.MUSHROOM_STEW).tab(VSTab.TAB)));
    public static final RegistryObject<Item> EXPONENTIAL_BEETROOT_SOUP = ITEMS.register("exponential_beetroot_soup", () -> new ExponentialStewItem(DEFAULT_BEHAVIOR, new Item.Properties().stacksTo(1).food(Foods.BEETROOT_SOUP).tab(VSTab.TAB)));
    public static final RegistryObject<Item> EXPONENTIAL_RABBIT_STEW = ITEMS.register("exponential_rabbit_stew", () -> new ExponentialStewItem(DEFAULT_BEHAVIOR, new Item.Properties().stacksTo(1).food(Foods.RABBIT_STEW).tab(VSTab.TAB)));
    public static final RegistryObject<Item> EXPONENTIAL_SUSPICIOUS_STEW = ITEMS.register("exponential_suspicious_stew", () -> new ExponentialStewItem(new ApplyMobEffectsBehavior(Lists.newArrayList()), new Item.Properties().stacksTo(1).food(Foods.SUSPICIOUS_STEW).tab(VSTab.TAB)));
    public static final RegistryObject<Item> EXPONENTIAL_MELTING_BEET_SOUP = ITEMS.register("exponential_melting_beet_soup", () -> new ExponentialStewItem(DEFAULT_BEHAVIOR, new Item.Properties().stacksTo(1).food(Foods.BEETROOT_SOUP).tab(VSTab.TAB)));
    public static final RegistryObject<Item> EXPONENTIAL_FUNGI_STEW = ITEMS.register("exponential_fungi_stew", () -> new ExponentialStewItem(DEFAULT_BEHAVIOR, new Item.Properties().stacksTo(1).food(Foods.MUSHROOM_STEW).tab(VSTab.TAB)));
    public static final RegistryObject<Item> EXPONENTIAL_END_FUNGI_STEW = ITEMS.register("exponential_end_fungi_stew", () -> new ExponentialStewItem(DEFAULT_BEHAVIOR, new Item.Properties().stacksTo(1).food(Foods.MUSHROOM_STEW).tab(VSTab.TAB)));
    public static final RegistryObject<Item> EXPONENTIAL_ALJAN_FUNGI_STEW = ITEMS.register("exponential_aljan_fungi_stew", () -> new ExponentialStewItem(DEFAULT_BEHAVIOR, new Item.Properties().stacksTo(1).food(Foods.MUSHROOM_STEW).tab(VSTab.TAB)));
    public static final RegistryObject<Item> EXPONENTIAL_WATER_BOWL = ITEMS.register("exponential_water_bowl", () -> new ExponentialStewItem(new ApplyMobEffectsBehavior(Lists.newArrayList(new VSEffectInstance(() -> Effects.WATER_BREATHING, 100))), new Item.Properties().stacksTo(1).food(VSFoods.FLUID_BOWL).tab(VSTab.TAB)));
    public static final RegistryObject<Item> EXPONENTIAL_MILK_BOWL = ITEMS.register("exponential_milk_bowl", () -> new ExponentialStewItem(new ClearMobEffectsBehavior(new ItemStack(Items.MILK_BUCKET)), new Item.Properties().stacksTo(1).food(VSFoods.MILK_BOWL).tab(VSTab.TAB)));
    public static final RegistryObject<Item> EXPONENTIAL_LAVA_BOWL = ITEMS.register("exponential_lava_bowl", () -> new ExponentialStewItem(new IgniteBehavior(100), new Item.Properties().stacksTo(1).food(VSFoods.FLUID_BOWL).tab(VSTab.TAB)));
    public static final RegistryObject<Item> EXPONENTIAL_SOUL_LAVA_BOWL = ITEMS.register("exponential_soul_lava_bowl", () -> new ExponentialStewItem(new IgniteBehavior(200), new Item.Properties().stacksTo(1).food(Foods.MUSHROOM_STEW).tab(VSTab.TAB)));
    public static final RegistryObject<Item> EXPONENTIAL_POWDER_SNOW_BOWL = ITEMS.register("exponential_powder_snow_bowl", () -> new ExponentialStewItem(DEFAULT_BEHAVIOR, new Item.Properties().stacksTo(1).food(Foods.APPLE).tab(VSTab.TAB)));
    public static final RegistryObject<Item> ENCHANTED_KNOWLEDGE_BOOK = ITEMS.register("enchanted_knowledge_book", () -> new EnchantedKnowledgeBookItem(new Item.Properties().rarity(Rarity.UNCOMMON).stacksTo(1)));

    public static Callable<ItemStackTileEntityRenderer> variantsISBERProvider() {
        return VSItemStackBlockEntityRenderer::new;
    }
}
