@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package melonystudios.variants.block.custom;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;