@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.junethewoods.variants.blocks;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;